<?php
putenv('SRMS_DB_NAME=eddt_srms_test');require dirname(__DIR__).'/app/bootstrap.php';
use Srms\Database as DB;use Srms\Registry as R;use Srms\Finance as F;use Srms\PropertyPayments as P;use Srms\PropertyPreview as Preview;use Srms\DashboardRepository as Dashboard;use Srms\Documents;
$checks=0;$files=[];function ok(bool $condition,string $label):void{global $checks;if(!$condition)throw new RuntimeException('FAIL '.$label);$checks++;echo "PASS $label\n";}function denied(callable $fn,string $label):void{try{$fn();}catch(DomainException $e){ok(true,$label);return;}throw new RuntimeException('Not denied: '.$label);}function state(string $p):array{return P::rows()[$p];}
DB::connection()->beginTransaction();try{
 $tag=substr(uuid(),0,8);$admin=Srms\Users::create(['full_name'=>'Map Test Admin','role_id'=>'00000000-0000-0000-0000-000000000001','phone_number'=>'+23329'.random_int(1000000,9999999),'password'=>'Testing-Password-123'],true);$_SESSION=['user_id'=>$admin,'session_version'=>1];
 $parcel=R::save('parcels',['parcel_number'=>'PAY-MAP-'.$tag,'boundary_geojson'=>'{"type":"Polygon","coordinates":[[[-0.13,5.61],[-0.12,5.61],[-0.12,5.62],[-0.13,5.61]]]}']);$p=R::save('properties',['property_number'=>'PAY-PROP-'.$tag,'parcel_id'=>$parcel]);$other=R::save('properties',['property_number'=>'OTHER-'.$tag]);
 ok(state($p)['payment_status']==='unbilled','Property without bills is gray/unbilled');
 $account=R::save('accounts',['account_number'=>'PAY-ACC-'.$tag,'property_id'=>$p,'opened_on'=>'2024-01-01']);$bills=[];
 foreach([2025=>'100',2026=>'200'] as $year=>$amount){$assessment=F::assessment(['property_id'=>$p,'assessment_year'=>$year,'annual_amount'=>$amount]);F::approve($assessment);$bills[]=F::issue($assessment,"$year-03-31");}
 ok(state($p)['payment_status']==='unpaid','Issued bills without payment are red');
 $payment=function(string $amount,string $method='bank')use($account){return F::payment(['account_id'=>$account,'amount'=>$amount,'payment_date'=>today(),'payment_method'=>$method,'request_key'=>uuid()]);};
 $partial=$payment('40');ok(state($p)['payment_status']==='partial','Partial payment is yellow');
 $over=$payment('300');ok(state($p)['payment_status']==='paid','Cleared bills are green');ok(Srms\Money::cmp(DB::scalar('SELECT credit_amount FROM accounts WHERE id=?',[$account]),'40')===0,'Excess remains credit');
 F::reverse($over,'Test reversal');ok(state($p)['payment_status']==='partial','Reversal restores partial status');F::reverse($partial,'Test reversal');ok(state($p)['payment_status']==='unpaid','Reversal of all payments restores red');
 $full=$payment('300','cash');F::adjust($bills[0],'penalty','30','Test historical debt');ok(state($p)['payment_status']==='partial'&&Srms\Money::cmp(state($p)['outstanding'],'30')===0,'Earlier-year debt prevents green status');
 denied(fn()=>P::exemption($p,true,''),'Exemption requires a reason');P::exemption($p,true,'Approved test exemption');ok(state($p)['payment_status']==='exempt','Exemption is white');ok(Srms\Money::cmp(state($p)['outstanding'],'30')===0,'Exemption preserves outstanding arrears');
 $next=F::assessment(['property_id'=>$p,'assessment_year'=>2027,'annual_amount'=>'100']);F::approve($next);denied(fn()=>F::issue($next,'2027-03-31'),'Exemption prevents new bills');ok(F::batch(2027,'2027-03-31')===0,'Annual batch skips exempt property');
 P::exemption($p,false,'Test exemption ended');F::issue($next,'2027-03-31');ok(state($p)['payment_status']==='partial','Removing exemption restores financial color');ok(DB::scalar("SELECT COUNT(*) FROM audit_logs WHERE entity_id=? AND action='property_exemption_changed'",[$p])==2,'Exemption decisions are audited');
 $rp=R::save('ratepayers',['ratepayer_number'=>'OWNER-'.$tag,'full_name'=>'Owner One']);$joint=R::save('ratepayers',['ratepayer_number'=>'JOINT-'.$tag,'full_name'=>'Owner Two']);R::ownership(['property_id'=>$p,'ratepayer_id'=>$rp,'start_date'=>'2024-01-01','ownership_percentage'=>'60']);R::ownership(['property_id'=>$p,'ratepayer_id'=>$joint,'start_date'=>'2024-01-01','ownership_percentage'=>'40']);
 $addPhoto=function(bool $visible,bool $primary,string $caption,?string $previous=null)use($p,$admin,&$files){$doc=Documents::store(file_get_contents(SRMS_ROOT.'/public/assets/eddt-logo.png'),'qa-photo.png','property_photo','properties',$p,$visible,$previous);$files[]=DB::scalar('SELECT storage_key FROM documents WHERE id=?',[$doc]);DB::insert('property_photos',['property_id'=>$p,'document_id'=>$doc,'caption'=>$caption,'is_primary'=>$primary?1:0,'created_by'=>$admin]);return $doc;};
 $internal=$addPhoto(false,true,'Internal primary');$old=$addPhoto(true,false,'Old photo');$current=$addPhoto(true,false,'Current visible photo',$old);
 $preview=Preview::get($p);ok(count($preview['owners'])===2,'Popup contains both current joint owners');ok(count($preview['photos'])===2&&$preview['photos'][0]['caption']==='Internal primary','Staff preview orders primary photo first and excludes obsolete version');
 $owner=Srms\Users::create(['full_name'=>'Owner One','role_id'=>'00000000-0000-0000-0000-000000000004','ratepayer_id'=>$rp,'phone_number'=>'+23328'.random_int(1000000,9999999),'password'=>'Testing-Password-123']);
 $d=Dashboard::data();ok(Srms\Money::cmp($d['collected'],'300')===0,'Dashboard excludes reversed payments');ok(Srms\Money::cmp(array_sum(array_column($d['methods'],'amount')),'300')===0,'Payment-method totals reconcile');ok(Srms\Money::cmp(array_sum(array_column($d['monthly'],'amount')),'300')===0,'Monthly totals reconcile');ok($d['statuses']['partial']===1&&$d['statuses']['unbilled']===1,'Dashboard uses shared property status');
 $_SESSION=['user_id'=>$owner,'session_version'=>1];$preview=Preview::get($p);ok(count($preview['photos'])===1&&$preview['photos'][0]['caption']==='Current visible photo','Owner cannot see internal or superseded photos');denied(fn()=>Preview::get($other),'Owner cannot access another property preview');ok(Dashboard::data()['property_count']===1,'Owner dashboard is scoped to owned property');denied(fn()=>P::exemption($p,true,'Attempt'),'Owner cannot grant exemption');
 $_SESSION=['user_id'=>$admin,'session_version'=>1];$nextOwner=R::save('ratepayers',['ratepayer_number'=>'NEXT-'.$tag,'full_name'=>'New Owner']);R::ownership(['property_id'=>$p,'ratepayer_id'=>$nextOwner,'previous_ratepayer_id'=>$rp,'start_date'=>today(),'ownership_percentage'=>'60']);
 $_SESSION=['user_id'=>$owner,'session_version'=>1];denied(fn()=>Preview::get($p),'Former owner loses popup access');ok(Dashboard::data()['property_count']===0,'Former owner loses dashboard property');
 $_SESSION=[];denied(fn()=>Preview::get($p),'Unauthenticated preview is rejected');
 $_SESSION=['user_id'=>$admin,'session_version'=>1];DB::update('users',$admin,['role_id'=>'00000000-0000-0000-0000-000000000002']);denied(fn()=>P::exemption($p,true,'Attempt'),'Billing Officer cannot grant exemption');
 echo "$checks dashboard/map checks passed. Test changes rolled back.\n";
}finally{DB::connection()->rollBack();foreach($files as $key){$path=(new Srms\LocalStorage())->path($key);if(is_file($path))unlink($path);}}