<?php
putenv('SRMS_DB_NAME=eddt_srms_rebuilt_test');putenv('SRMS_STORAGE_PATH=C:/xampp/htdocs/srms/var/rebuilt-test-storage');require dirname(__DIR__).'/app/bootstrap.php';
use Srms\Database as DB;use Srms\CorrespondenceBatch as Batch;use Srms\PropertyContactReport as Contacts;
\Srms\CorrespondenceStorageSchema::migrate();$checks=0;$baseline=DB::all('SELECT storage_key FROM documents');$baseline=array_column($baseline,'storage_key');$files=[];
function check($v,$label){global $checks;if(!$v)throw new RuntimeException('FAIL '.$label);$checks++;echo "PASS $label\n";}
function denied($fn,$label){try{$fn();}catch(DomainException $e){check(true,$label);return;}throw new RuntimeException('FAIL allowed: '.$label);}
$admin=DB::one("SELECT u.* FROM users u JOIN roles r ON r.id=u.role_id WHERE r.name='Administrator' LIMIT 1");$_SESSION=['user_id'=>$admin['id'],'session_version'=>$admin['session_version']];DB::connection()->beginTransaction();
try{
 $number='EDDT99001001';$owner=DB::scalar('SELECT primary_ratepayer_id FROM parcel_accounts WHERE account_number=?',[$number]);Srms\Registry::phone(['ratepayer_id'=>$owner,'phone_number'=>'+233241234567']);Srms\Registry::phone(['ratepayer_id'=>$owner,'phone_number'=>'+233241234568']);
 $rows=Contacts::rows(['q'=>$number]);check(count($rows)===1,'Property filter');check(str_contains($rows[0]['owner_phones'],'+233241234567')&&str_contains($rows[0]['owner_phones'],'+233241234568'),'All owner contacts exported');check($rows[0]['division_code']==='99'&&$rows[0]['block_code']==='001','Identifiers preserve leading zeroes');
 $joint=Srms\Registry::save('ratepayers',['ratepayer_number'=>'BATCH-JOINT','full_name'=>'Joint export owner','email'=>'joint@example.test']);Srms\Registry::ownership(['account_number'=>$number,'ratepayer_id'=>$joint,'start_date'=>today(),'ownership_percentage'=>'50']);check(count(Contacts::rows(['q'=>$number]))===2,'Joint owners produce distinct rows');
 $unowned='EDDT97001001';Srms\Registry::save('parcels',['account_number'=>$unowned]);check(count(Contacts::rows(['q'=>$unowned]))===1,'Unassigned properties included');check(Contacts::rows(['q'=>'NO-SUCH-ACCOUNT'])===[],'Empty export filter');check(Contacts::csvCell('=HYPERLINK("bad")')[0]==="'",'CSV formula neutralized');check(Contacts::csvCell('+233241234567')[0]==="'",'CSV phone protected');
 $d=['type'=>'demand_notice','year'=>2026,'printed_date'=>today(),'accounts'=>'EDDT99001001, EDDT99001002, EDDT99001003','request_key'=>uuid()];$p=Batch::parameters($d);$eligible=Batch::candidates($p);check(count($eligible)===2,'Paid accounts excluded from demand batch');$id=Batch::create($d);check(Batch::create($d)===$id,'Duplicate create token is idempotent');$result=Batch::run($id);check($result['completed']===2&&$result['status']==='completed','Demand batch completes');$count=DB::scalar('SELECT COUNT(*) FROM correspondence');Batch::run($id);check(DB::scalar('SELECT COUNT(*) FROM correspondence')===$count,'Repeated batch run does not duplicate letters');$pdf=Batch::merged($id,uuid());check(str_starts_with($pdf,'%PDF-'),'Combined PDF produced');file_put_contents(SRMS_ROOT.'/var/qa/batch-demand-test.pdf',$pdf);$reader=new setasign\Fpdi\Fpdi();check($reader->setSourceFile(SRMS_ROOT.'/var/qa/batch-demand-test.pdf')===2,'Combined demand PDF contains both pages');
 $inv=['type'=>'invitation','year'=>2026,'printed_date'=>today(),'period_from'=>'2026-10-01','period_to'=>'2026-10-31','accounts'=>'EDDT99001001 EDDT99001002 EDDT99001004 EDDT99001005','request_key'=>uuid()];$bid=Batch::create($inv);$r=Batch::run($bid);check($r['completed']===3&&$r['pending']===1,'Batch pauses after small chunk');$r=Batch::run($bid);check($r['completed']===4&&$r['pending']===0,'Interrupted batch resumes');file_put_contents(SRMS_ROOT.'/var/qa/batch-invitation-test.pdf',Batch::merged($bid,uuid()));check($reader->setSourceFile(SRMS_ROOT.'/var/qa/batch-invitation-test.pdf')===4,'Combined invitation has all pages');
 denied(fn()=>Batch::parameters($inv+[])&&Batch::parameters(array_replace($inv,['period_to'=>'2026-09-01'])),'Invalid invitation dates rejected');
 $retry=Batch::create(array_replace($inv,['accounts'=>'EDDT99001001','request_key'=>uuid()]));$saved=Batch::get($retry)['parameters_json'];$bad=json_decode($saved,true);$bad['period_from']='invalid';DB::update('correspondence_batches',$retry,['parameters_json'=>json_encode($bad)]);$r=Batch::run($retry);check($r['failed']===1,'Failed item tracked');DB::update('correspondence_batches',$retry,['parameters_json'=>$saved]);$r=Batch::run($retry);check($r['completed']===1&&$r['failed']===0,'Failed item can retry');
 $paid=Batch::create(array_replace($d,['accounts'=>'EDDT99001002','request_key'=>uuid()]));Srms\Finance::payment(['account_number'=>'EDDT99001002','amount'=>'2000','payment_date'=>today(),'payment_method'=>'cash','request_key'=>uuid()]);$r=Batch::run($paid);check($r['skipped']===1,'Paid-after-preview recipient is skipped');
 foreach(['Read-Only Auditor','Property Owner'] as $role){$u=DB::one('SELECT u.* FROM users u JOIN roles r ON r.id=u.role_id WHERE r.name=?',[$role]);$_SESSION=['user_id'=>$u['id'],'session_version'=>$u['session_version']];if($role==='Property Owner')denied(fn()=>Batch::get($id),$role.' cannot access batch');else check(Batch::get($id)['id']===$id,'Auditor can read batch');if($role==='Property Owner')denied(fn()=>Contacts::rows(), 'Owner cannot export staff contact list');else check(count(Contacts::rows())>0,'Auditor can export contact report');}
 echo "$checks export and batch checks passed.\n";
}finally{$files=array_diff(array_column(DB::all('SELECT storage_key FROM documents'),'storage_key'),$baseline);DB::connection()->rollBack();foreach($files as $file){$path=(new Srms\LocalStorage())->path($file);if(is_file($path))unlink($path);}}
