<?php
if(PHP_SAPI!=='cli')exit(1);
$root=dirname(__DIR__);$base='http://127.0.0.1:8081/index.php';$access=file_get_contents($root.'/var/demo-access.txt');preg_match('/Password: (\S+)/',$access,$m);$cookie=$root.'/var/qa/http-cookies.txt';$checks=0;
function request(string $route,array $data=[],bool $post=false): array {global $base,$cookie;$ch=curl_init($base.'?'.$route);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_COOKIEFILE=>$cookie,CURLOPT_COOKIEJAR=>$cookie,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_TIMEOUT=>30]);if($post){curl_setopt($ch,CURLOPT_POST,true);curl_setopt($ch,CURLOPT_POSTFIELDS,http_build_query($data));}$body=curl_exec($ch);$status=curl_getinfo($ch,CURLINFO_HTTP_CODE);$type=curl_getinfo($ch,CURLINFO_CONTENT_TYPE);$error=curl_error($ch);curl_close($ch);if($body===false)throw new RuntimeException($error);return [$status,$body,$type];}
function ok(bool $v,string $label): void {global $checks;if(!$v)throw new RuntimeException('FAIL '.$label);$checks++;echo "PASS $label\n";}
[$status,$body]=request('r=login');preg_match('/name="csrf" value="([^"]+)"/',$body,$match);ok($status===200&&isset($match[1]),'Login page and CSRF');[$status]=request('r=login',['csrf'=>'bad','phone'=>'+233200000001','password'=>$m[1]],true);ok($status===422,'CSRF rejection');[$status]=request('r=login',['csrf'=>$match[1],'phone'=>'+233200000001','password'=>$m[1]],true);ok($status===302,'Phone/password login');
foreach(['dashboard','register&type=properties','register&type=accounts','register&type=ratepayers','register&type=parcels','register&type=spatial_layers','edit&type=properties','edit&type=parcels','billing','payments','documents','reports','imports','users','settings','password','map','map-data','lookups&type=properties'] as $route){[$status,$body]=request('r='.$route);ok($status===200&&!str_contains($body,'Fatal error')&&!str_contains($body,'Warning:'),'HTTP '.$route);}
[$status,$body]=request('r=map-data');$features=json_decode($body,true);ok(count($features['features']??[])===6,'Map returns six authorized demo parcels');
[$status,$body]=request('r=property-preview&id='.$features['features'][0]['properties']['id']);$preview=json_decode($body,true);ok($status===200&&isset($preview['owners'],$preview['photos']),'Authenticated property preview');
[$status]=request('r=property-preview&id=missing');ok($status===422,'Missing preview record rejected');
foreach(['xlsx','pdf'] as $format){[$status,$body,$mime]=request('r=export&type=billing&format='.$format);ok($status===200&&str_starts_with($body,$format==='xlsx'?'PK':'%PDF-'),'Real '.$format.' report export');}
[$status,$body]=request('r=dashboard');preg_match('/name="csrf" value="([^"]+)"/',$body,$match);[$status,$zip]=request('r=backup',['csrf'=>$match[1]],true);ok($status===200&&str_starts_with($zip,'PK'),'Trust export endpoint');
[$status]=request('r=logout',['csrf'=>$match[1]],true);ok($status===302,'Logout');[$status]=request('r=map-data');ok($status===302,'Unauthenticated map endpoint protected');
[$status]=request('r=property-preview&id=missing');ok($status===302,'Unauthenticated photo preview protected');
if(is_file($cookie))unlink($cookie);echo "$checks HTTP checks passed.\n";
