<?php
putenv('SRMS_DB_NAME=eddt_workflow_v2_test');putenv('SRMS_STORAGE_PATH=C:/xampp/htdocs/srms/var/workflow-v2-test-storage');require dirname(__DIR__).'/app/bootstrap.php';
use Srms\Database as DB;use Srms\PropertyWorkflow as Flow;use Srms\Registry;use Srms\Finance;use Srms\DashboardRepository as Dash;use Srms\Reports;
$n=0;function ok($v,$label){global $n;if(!$v)throw new RuntimeException('FAIL '.$label);$n++;echo "PASS $label\n";}function asRole($role){$u=DB::one('SELECT u.* FROM users u JOIN roles r ON r.id=u.role_id WHERE r.name=? LIMIT 1',[$role]);$_SESSION=['user_id'=>$u['id'],'session_version'=>$u['session_version']];return $u;}function denied($fn,$label){try{$fn();}catch(DomainException $e){ok(true,$label);return;}throw new RuntimeException('Allowed '.$label);}
\Srms\CorrespondenceStorageSchema::migrate();$files=[];DB::connection()->beginTransaction();try{
asRole('Administrator');ok(!DB::scalar("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=? AND table_name LIKE 'legacy_%'",[config('db_name')]),'Clean schema has no legacy tables');ok(!DB::scalar("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=? AND column_name LIKE 'legacy_%'",[config('db_name')]),'Clean schema has no legacy foreign-key columns');
$a='EDDT95001001';Registry::save('parcels',['account_number'=>$a,'locality'=>'Workflow test']);ok(Flow::get($a)['stage']==='owner','Registration starts at owner assignment');denied(fn()=>Flow::act(['account_number'=>$a,'step'=>'assessment','annual_amount'=>'1200']),'Cannot skip owner assignment');denied(fn()=>Finance::assessment(['account_number'=>$a,'assessment_year'=>date('Y'),'annual_amount'=>'10']),'Direct assessment cannot bypass owner requirement');$owner=DB::scalar('SELECT id FROM ratepayers LIMIT 1');Registry::ownership(['account_number'=>$a,'ratepayer_id'=>$owner,'start_date'=>today()]);ok(Flow::get($a)['stage']==='assessment','Assigned owner unlocks assessment');
asRole('Billing Officer');Flow::act(['account_number'=>$a,'step'=>'assessment','annual_amount'=>'1200']);ok(Flow::get($a)['stage']==='approval','Assessment awaits approval');denied(fn()=>Flow::act(['account_number'=>$a,'step'=>'assessment','annual_amount'=>'1200']),'Repeated assessment does not duplicate');denied(fn()=>Flow::act(['account_number'=>$a,'step'=>'approval']),'Billing Officer cannot approve');asRole('Administrator');Flow::act(['account_number'=>$a,'step'=>'approval']);ok(Flow::get($a)['stage']==='billing','Approved assessment unlocks bill');Flow::act(['account_number'=>$a,'step'=>'billing','due_date'=>today()]);ok(Flow::get($a)['stage']==='payment','Issued bill unlocks payment');denied(fn()=>Flow::act(['account_number'=>$a,'step'=>'billing','due_date'=>today()]),'Repeated issue cannot duplicate bill');
$payment=Finance::payment(['account_number'=>$a,'amount'=>'1200','payment_date'=>today(),'payment_method'=>'cash','request_key'=>uuid()]);ok(Flow::get($a)['stage']==='complete','Fully paid property up to date');
foreach([['type'=>'receipt','payment_id'=>$payment],['type'=>'demand_notice','bill_id'=>Flow::get($a)['bill_id']],['type'=>'invitation','period_from'=>today(),'period_to'=>today()]] as $d){$id=Srms\Correspondence::generate($d+['account_number'=>$a]);$record=Srms\CorrespondenceOutput::record($id);$out=Srms\CorrespondenceOutput::output($id,'preview',uuid());ok(!$record['generated_document_id']&&str_starts_with($out['bytes'],'%PDF-'),'On-demand '.$d['type'].' generated in clean schema');}
$year=(int)date('Y');$dash=Dash::data(['year'=>$year]);ok(count($dash['monthly'])===12&&$dash['monthly'][0]['month']===$year.'-01','Year filter produces January to December');$collection=Reports::rows('collections',['status'=>'posted','from'=>$year.'-01-01','to'=>$year.'-12-31']);$sum='0';foreach($collection as $r)$sum=Srms\Money::add($sum,$r['amount']);$chart='0';foreach($dash['monthly'] as $r)$chart=Srms\Money::add($chart,$r['amount']);ok(Srms\Money::cmp($sum,$chart)===0,'Monthly chart and drill-down totals reconcile');$billing=Reports::rows('billing',['year'=>$year,'account_number'=>$a]);ok(count($billing)===1&&$billing[0]['account_number']===$a,'Workflow bill report filters by Account and year');denied(fn()=>Dash::data(['year'=>'oops']),'Invalid dashboard year rejected');
$cash=Reports::rows('collections',['method'=>'cash','status'=>'posted']);ok(!array_filter($cash,fn($r)=>$r['payment_method']!=='cash'||$r['status']!=='posted'),'Payment method drill-down is scoped');
asRole('Read-Only Auditor');denied(fn()=>Flow::act(['account_number'=>$a,'step'=>'approval']),'Auditor cannot mutate workflow');$u=asRole('Property Owner');$owned=Flow::rows();ok(!array_filter($owned,function($r){try{Srms\Auth::property($r['account_number']);return false;}catch(DomainException $e){return true;}}),'Owner workflow rows are authorized');denied(fn()=>Flow::act(['account_number'=>$a,'step'=>'approval']),'Owner cannot mutate workflow');$own=Dash::data(['year'=>$year]);ok($own['property_count']<13,'Owner chart excludes other properties');
asRole('Administrator');$path=SRMS_ROOT.'/var/qa/v2-trust-test.zip';Srms\Backup::create($path);ok(is_file($path),'Trust export supports clean schema');unlink($path);echo "$n MySQL rebuild checks passed.\n";
}finally{DB::connection()->rollBack();foreach($files as $file){$path=(new Srms\LocalStorage())->path($file);if(is_file($path))unlink($path);}}
