<?php
declare(strict_types=1);
// All integration writes run in a transaction against an isolated database.
putenv('SRMS_DB_NAME=eddt_srms_test');
require dirname(__DIR__).'/app/bootstrap.php';
use Srms\Database as DB;use Srms\Auth;use Srms\Registry;use Srms\Finance;use Srms\Money;use Srms\Documents;use Srms\Reports;
$checks=0;$files=[];
session_save_path(SRMS_ROOT.'/var/sessions');session_start();ob_start();
function check(bool $condition,string $message): void {global $checks;if(!$condition)throw new RuntimeException('FAIL: '.$message);$checks++;echo "PASS $message\n";}
function denied(callable $fn,string $message): void {try{$fn();}catch(DomainException|PDOException|JsonException $e){check(true,$message);return;}throw new RuntimeException('FAIL (not rejected): '.$message);}
function loginAs(string $id): void {$_SESSION=['user_id'=>$id,'session_version'=>1];}
DB::connection()->beginTransaction();
try{
 $tag=substr(uuid(),0,8);$admin=Srms\Users::create(['full_name'=>'Test Administrator','role_id'=>'00000000-0000-0000-0000-000000000001','phone_number'=>'+23329'.random_int(1000000,9999999),'password'=>'Testing-Password-123'],true);loginAs($admin);
 check(money('999999999999999.9999')==='1,000,000,000,000,000.00','Large money display rounds without float precision loss');check(money('-0.0050')==='-0.01','Negative money display rounds correctly');check(Money::add('0.1000','0.2000')==='0.3000','Decimal arithmetic');denied(fn()=>Money::parse('1e4'),'Reject exponent amounts');denied(fn()=>Money::parse('-1'),'Reject negative payments');
 $rp=Registry::save('ratepayers',['ratepayer_number'=>'TEST-'.$tag,'full_name'=>'Test Owner','ratepayer_type'=>'individual']);$rp2=Registry::save('ratepayers',['ratepayer_number'=>'TEST2-'.$tag,'full_name'=>'Second Owner','ratepayer_type'=>'corporate','organization_name'=>'Test Company Ltd']);
 $p=Registry::save('properties',['property_number'=>'PROP-'.$tag,'land_id'=>'LAND-'.$tag,'plot_size'=>'2.5','plot_size_unit'=>'acre']);$p2=Registry::save('properties',['property_number'=>'PROP2-'.$tag]);
 Registry::ownership(['property_id'=>$p,'ratepayer_id'=>$rp,'start_date'=>'2025-01-01','ownership_percentage'=>'50']);Registry::ownership(['property_id'=>$p,'ratepayer_id'=>$rp2,'start_date'=>'2025-01-01','ownership_percentage'=>'50']);
 denied(fn()=>Registry::ownership(['property_id'=>$p,'ratepayer_id'=>$rp,'start_date'=>'2025-01-01']),'Reject overlapping ownership');
 $a=Registry::save('accounts',['account_number'=>'ACC-'.$tag,'property_id'=>$p,'primary_ratepayer_id'=>$rp,'opened_on'=>'2025-01-01']);denied(fn()=>Registry::save('accounts',['account_number'=>'ACC2-'.$tag,'property_id'=>$p,'opened_on'=>'2025-01-01']),'One active account per property');
 $assessment=Finance::assessment(['property_id'=>$p,'assessment_year'=>2025,'annual_amount'=>'100.1000']);denied(fn()=>Finance::issue($assessment,'2025-12-31'),'Approval required before billing');Finance::approve($assessment);$bill=Finance::issue($assessment,'2025-12-31');check(Finance::issue($assessment,'2025-12-31')===$bill,'Duplicate annual issue is idempotent');
 $key=uuid();$pay=Finance::payment(['account_id'=>$a,'amount'=>'40.0000','payment_date'=>today(),'payment_method'=>'cash','request_key'=>$key]);check(DB::scalar('SELECT paid_amount FROM ground_rent_bills WHERE id=?',[$bill])==='40.0000','Partial payment allocated');check(Finance::payment(['account_id'=>$a,'amount'=>'40','payment_date'=>today(),'payment_method'=>'cash','request_key'=>$key])===$pay,'Duplicate payment submission idempotent');
 $pay2=Finance::payment(['account_id'=>$a,'amount'=>'100','payment_date'=>today(),'payment_method'=>'bank','request_key'=>uuid()]);check(DB::scalar('SELECT credit_amount FROM accounts WHERE id=?',[$a])==='39.9000','Overpayment retained as credit');
 $assessment2=Finance::assessment(['property_id'=>$p,'assessment_year'=>2026,'annual_amount'=>'200']);Finance::approve($assessment2);$bill2=Finance::issue($assessment2,'2026-12-31');check(DB::scalar('SELECT paid_amount FROM ground_rent_bills WHERE id=?',[$bill2])==='39.9000','New bill consumes credit');
 Finance::adjust($bill2,'penalty','10','Late payment');Finance::adjust($bill2,'adjustment','-5','Correction');check(DB::scalar('SELECT adjustment_amount FROM ground_rent_bills WHERE id=?',[$bill2])==='-5.0000','Signed adjustment recorded');denied(fn()=>Finance::adjust($bill2,'adjustment','-999','Invalid'),'Reject negative bill total');
 Finance::reverse($pay2,'Duplicate bank entry');check(DB::scalar('SELECT paid_amount FROM ground_rent_bills WHERE id=?',[$bill])==='40.0000','Reversal rebuilds oldest-bill allocation');check(DB::scalar('SELECT paid_amount FROM ground_rent_bills WHERE id=?',[$bill2])==='0.0000','Reversal removes future allocation');denied(fn()=>Finance::reverse($pay2,'Again'),'Reject repeat reversal');
 $phone='+23328'.random_int(1000000,9999999);Registry::phone(['ratepayer_id'=>$rp,'phone_number'=>$phone,'is_verified'=>1,'can_login'=>1]);$owner=Srms\Users::create(['full_name'=>'Test Owner Login','role_id'=>'00000000-0000-0000-0000-000000000004','ratepayer_id'=>$rp,'phone_number'=>$phone,'password'=>'Testing-Password-123']);
 check(Auth::login($phone,'Testing-Password-123'),'Verified owner phone authenticates');check(Auth::user()['id']===$owner,'Phone resolves to linked owner account');loginAs($admin);$secondary='+23325'.random_int(1000000,9999999);Registry::phone(['ratepayer_id'=>$rp,'phone_number'=>$secondary,'is_verified'=>1,'can_login'=>1]);check(Auth::login($secondary,'Testing-Password-123')&&Auth::user()['id']===$owner,'Secondary phone resolves to same owner');loginAs($admin);Registry::phone(['ratepayer_id'=>$rp,'phone_number'=>$secondary,'is_verified'=>1,'can_login'=>0]);check(!Auth::login($secondary,'Testing-Password-123'),'Disabled phone cannot authenticate');Registry::phone(['ratepayer_id'=>$rp,'phone_number'=>$secondary,'is_verified'=>0,'can_login'=>1]);check(!Auth::login($secondary,'Testing-Password-123'),'Unverified phone cannot authenticate');denied(fn()=>Srms\Users::create(['full_name'=>'Collision','role_id'=>'00000000-0000-0000-0000-000000000002','phone_number'=>$phone,'password'=>'Testing-Password-123']),'Phone cannot identify both staff and another owner');
 $pdf=Srms\Correspondence::pdf('<h1>Test document</h1>');$doc=Documents::store($pdf,'test.pdf','test','properties',$p,true);$files[]=DB::scalar('SELECT storage_key FROM documents WHERE id=?',[$doc]);$internal=Documents::store($pdf,'internal.pdf','test','properties',$p,false);$files[]=DB::scalar('SELECT storage_key FROM documents WHERE id=?',[$internal]);$newDoc=Documents::store($pdf,'test-v2.pdf','test','properties',$p,true,$doc);$files[]=DB::scalar('SELECT storage_key FROM documents WHERE id=?',[$newDoc]);check((int)DB::scalar('SELECT is_current_version FROM documents WHERE id=?',[$doc])===0,'Document version history retained');denied(fn()=>Documents::store('<?php echo 1;','fake.pdf','test','properties',$p),'Reject executable content disguised as PDF');
 loginAs($owner);Auth::property($p);check(true,'Owner can access jointly owned property');denied(fn()=>Auth::property($p2),'Owner cannot access other property');denied(fn()=>Finance::payment(['account_id'=>$a,'amount'=>'1']),'Owner cannot post payments');check(Documents::allowed(DB::one('SELECT * FROM documents WHERE id=?',[$doc])),'Owner-visible document access');check(!Documents::allowed(DB::one('SELECT * FROM documents WHERE id=?',[$internal])),'Internal document hidden from owner');check(count(Reports::rows('balances'))===1,'Owner report row isolation');denied(fn()=>Reports::rows('audit'),'Owner denied audit report');
 loginAs($admin);$rp3=Registry::save('ratepayers',['ratepayer_number'=>'TEST3-'.$tag,'full_name'=>'New Owner']);Registry::ownership(['property_id'=>$p,'ratepayer_id'=>$rp3,'previous_ratepayer_id'=>$rp,'start_date'=>today()]);loginAs($owner);denied(fn()=>Auth::property($p),'Former owner loses property access');check(!Documents::allowed(DB::one('SELECT * FROM documents WHERE id=?',[$doc])),'Former owner loses linked document access');loginAs($admin);check(DB::scalar('SELECT account_number FROM accounts WHERE id=?',[$a])==='ACC-'.$tag,'Transfer preserves land account');
 $letter=Srms\Correspondence::generate(['type'=>'demand_notice','account_id'=>$a,'bill_id'=>$bill2]);$files[]=DB::scalar('SELECT storage_key FROM documents WHERE id=?',[$letter]);check(DB::scalar('SELECT COUNT(*) FROM correspondence WHERE generated_document_id=?',[$letter])==1,'Demand PDF archived with snapshot');$receipt=Srms\Correspondence::generate(['type'=>'receipt','account_id'=>$a,'payment_id'=>$pay]);$files[]=DB::scalar('SELECT storage_key FROM documents WHERE id=?',[$receipt]);check(DB::scalar('SELECT mime_type FROM documents WHERE id=?',[$receipt])==='application/pdf','Receipt PDF generated');
 $invite=Srms\Correspondence::generate(['type'=>'invitation','account_id'=>$a,'period_from'=>'2026-10-20','period_to'=>'2026-12-10']);$files[]=DB::scalar('SELECT storage_key FROM documents WHERE id=?',[$invite]);check(true,'Invitation PDF generated');
 denied(fn()=>Registry::geometry('{"type":"Polygon","coordinates":[[[0,0],[1,0],[1,1]]]}'),'Reject unclosed polygon');denied(fn()=>Registry::geometry('{"type":"Point","coordinates":[999,0]}'),'Reject invalid coordinates');check(str_contains(Registry::geometry('{"type":"Point","coordinates":[-0.13,5.61]}'),'Point'),'Valid portable geometry');
 denied(fn()=>Srms\Imports::normalize('properties',['property_number'=>'PROP-'.$tag]),'Import detects existing property');denied(fn()=>Srms\Imports::normalize('opening_balances',['account_number'=>'ACC-'.$tag,'billing_year'=>'2025','amount'=>'1','due_date'=>'2025-12-31','reference'=>'legacy']),'Import detects duplicate annual opening balance');
 $batch=DB::insert('import_batches',['source_filename'=>'test.csv','entity_type'=>'properties','status'=>'validated','total_rows'=>2,'valid_rows'=>2,'invalid_rows'=>0,'created_by'=>$admin]);foreach([1,2] as $n)DB::insert('import_rows',['batch_id'=>$batch,'row_number'=>$n+1,'row_data_json'=>json_encode(['property_number'=>'IMPORTED-'.$tag.'-'.$n]),'status'=>'valid']);check(Srms\Imports::commit($batch)===0,'Validated import commits');check(DB::scalar("SELECT COUNT(*) FROM import_rows WHERE batch_id=? AND status='imported'",[$batch])==2,'Import tracks target records');denied(fn()=>Srms\Imports::commit($batch),'Completed import cannot be repeated');
 $resumeBatch=DB::insert('import_batches',['source_filename'=>'resume.csv','entity_type'=>'properties','status'=>'validated','total_rows'=>101,'valid_rows'=>101,'invalid_rows'=>0,'created_by'=>$admin]);for($n=1;$n<=101;$n++)DB::insert('import_rows',['batch_id'=>$resumeBatch,'row_number'=>$n+1,'row_data_json'=>json_encode(['property_number'=>'RESUME-'.$tag.'-'.$n]),'status'=>'valid']);check(Srms\Imports::commit($resumeBatch)===1,'Import pauses after configured chunk');check(Srms\Imports::commit($resumeBatch)===0,'Import resumes remaining rows');check(DB::scalar("SELECT COUNT(*) FROM import_rows WHERE batch_id=? AND status='imported'",[$resumeBatch])==101,'Resumed import does not repeat rows');
 $before=(int)DB::scalar('SELECT COUNT(*) FROM properties');try{DB::transaction(function()use($tag){Registry::save('properties',['property_number'=>'ROLLBACK-'.$tag]);throw new DomainException('Intentional rollback');});}catch(DomainException){}check((int)DB::scalar('SELECT COUNT(*) FROM properties')===$before,'Nested transaction rollback preserves consistency');
 $auditor=Srms\Users::create(['full_name'=>'Test Auditor','role_id'=>'00000000-0000-0000-0000-000000000003','phone_number'=>'+23327'.random_int(1000000,9999999),'password'=>'Testing-Password-123']);loginAs($auditor);denied(fn()=>Registry::save('properties',['property_number'=>'FORBIDDEN']),'Auditor cannot edit records');check(count(Reports::rows('audit'))>0,'Auditor can read audit history');loginAs($admin);
 $export=SRMS_ROOT.'/var/test-export.zip';Srms\Backup::create($export);$z=new ZipArchive();$z->open($export);$manifest=json_decode($z->getFromName('manifest.json'),true);foreach($manifest['files'] as $path=>$hash)check(hash('sha256',$z->getFromName($path))===$hash,'Export integrity '.$path);check(!str_contains($z->getFromName('data/users.json'),'password_hash'),'Trust export excludes credentials');$z->close();unlink($export);
 $book=new PhpOffice\PhpSpreadsheet\Spreadsheet();$book->getActiveSheet()->setCellValueExplicit('A1','=1+1',PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING);$xlsx=SRMS_ROOT.'/var/test.xlsx';(new PhpOffice\PhpSpreadsheet\Writer\Xlsx($book))->save($xlsx);$loaded=PhpOffice\PhpSpreadsheet\IOFactory::load($xlsx);check($loaded->getActiveSheet()->getCell('A1')->getDataType()==='s','Excel export supports formula-safe text');unlink($xlsx);
}catch(Throwable $e){echo $e."\n";$failed=true;}finally{if(DB::connection()->inTransaction())DB::connection()->rollBack();foreach($files as $key){$path=(new Srms\LocalStorage())->path($key);if(is_file($path))unlink($path);}}
if(!empty($failed))exit(1);echo "$checks checks passed. Test transactions rolled back.\n";
