<?php
putenv('SRMS_DB_NAME=eddt_srms_demo');require dirname(__DIR__).'/app/bootstrap.php';
use Srms\Database as DB;
if(PHP_SAPI!=='cli')exit(1);
$base='http://127.0.0.1:8081/index.php';$cookie=SRMS_ROOT.'/var/qa/upload-cookies.txt';preg_match('/Password: (\S+)/',file_get_contents(SRMS_ROOT.'/var/demo-access.txt'),$m);
function callApp(string $r,array $data=[],bool $multipart=false): array{global $base,$cookie;$ch=curl_init($base.'?r='.$r);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_COOKIEFILE=>$cookie,CURLOPT_COOKIEJAR=>$cookie,CURLOPT_TIMEOUT=>30]);if($data)curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$multipart?$data:http_build_query($data)]);$body=curl_exec($ch);$status=curl_getinfo($ch,CURLINFO_HTTP_CODE);if($body===false)throw new RuntimeException(curl_error($ch));curl_close($ch);return [$status,$body];}
[$s,$body]=callApp('login');preg_match('/name="csrf" value="([^"]+)"/',$body,$csrf);[$s]=callApp('login',['csrf'=>$csrf[1],'phone'=>'+233200000001','password'=>$m[1]]);if($s!==302)throw new RuntimeException('Login failed.');[$s,$body]=callApp('dashboard');preg_match('/name="csrf" value="([^"]+)"/',$body,$csrf);$property=DB::one("SELECT id FROM properties WHERE property_number='DEMO-PROP-001'");$file=SRMS_ROOT.'/var/qa/upload-fixture.png';$img=imagecreatetruecolor(320,200);$bg=imagecolorallocate($img,190,215,189);imagefill($img,0,0,$bg);$ink=imagecolorallocate($img,25,90,65);imagestring($img,5,70,90,'UAT PROPERTY PHOTO',$ink);imagepng($img,$file);imagedestroy($img);
[$s,$body]=callApp('upload',['csrf'=>$csrf[1],'entity_type'=>'properties','entity_id'=>$property['id'],'document_type'=>'property_photo','photo'=>'1','owner_visible'=>'1','is_primary'=>'1','caption'=>'UAT upload test','taken_at'=>today(),'display_order'=>'1','file'=>new CURLFile($file,'image/png','uat-photo.png')],true);if($s!==302)throw new RuntimeException('Photo upload failed: '.$s.' '.strip_tags($body));echo "PASS Multipart image upload and primary photo\n";
$doc=DB::one("SELECT d.* FROM documents d JOIN property_photos p ON p.document_id=d.id WHERE p.property_id=? AND p.is_primary=1",[$property['id']]);[$s,$body]=callApp('download&id='.$doc['id']);if($s!==200||hash('sha256',$body)!==$doc['sha256_hash'])throw new RuntimeException('Document download mismatch.');echo "PASS Download matches original hash\n";
$tag=substr(uuid(),0,8);$csv=SRMS_ROOT.'/var/qa/import-fixture.csv';file_put_contents($csv,"property_number,land_id,plot_size,plot_size_unit,land_description,locality,digital_address\nHTTP-$tag,HTTP-LAND-$tag,0.5,acre,Import fixture,Tse Addo,\n");[$s,$body]=callApp('import-upload',['csrf'=>$csrf[1],'type'=>'properties','file'=>new CURLFile($csv,'text/csv','uat-import.csv')],true);if($s!==302)throw new RuntimeException('CSV upload failed: '.strip_tags($body));$batch=DB::one("SELECT * FROM import_batches WHERE source_filename='uat-import.csv' ORDER BY created_at DESC LIMIT 1");if(!$batch||$batch['valid_rows']!=1||$batch['invalid_rows']!=0)throw new RuntimeException('CSV validation mismatch.');echo "PASS CSV dry-run upload validates without importing\n";if(DB::scalar('SELECT COUNT(*) FROM properties WHERE property_number=?',['HTTP-'.$tag])!=0)throw new RuntimeException('Dry-run mutated register.');[$s]=callApp('import-commit',['csrf'=>$csrf[1],'id'=>$batch['id']]);if($s!==302||DB::scalar('SELECT COUNT(*) FROM properties WHERE property_number=?',['HTTP-'.$tag])!=1)throw new RuntimeException('Import commit failed.');echo "PASS Administrator commits validated CSV\n";
$book=new PhpOffice\PhpSpreadsheet\Spreadsheet();$book->getActiveSheet()->fromArray([Srms\Imports::TEMPLATES['ratepayers'],['XLSX-'.$tag,'Spreadsheet Owner','individual','','','']]);$xlsx=SRMS_ROOT.'/var/qa/import-fixture.xlsx';(new PhpOffice\PhpSpreadsheet\Writer\Xlsx($book))->save($xlsx);[$s,$body]=callApp('import-upload',['csrf'=>$csrf[1],'type'=>'ratepayers','file'=>new CURLFile($xlsx,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','uat-import.xlsx')],true);if($s!==302)throw new RuntimeException('Excel upload failed: '.strip_tags($body));$batch=DB::one("SELECT * FROM import_batches WHERE source_filename='uat-import.xlsx' ORDER BY created_at DESC LIMIT 1");if(!$batch||$batch['valid_rows']!=1)throw new RuntimeException('Excel validation failed.');echo "PASS XLSX dry-run validates\n";
callApp('logout',['csrf'=>$csrf[1]]);[$s]=callApp('download&id='.$doc['id']);if($s!==302)throw new RuntimeException('Anonymous download was allowed.');echo "PASS Anonymous direct document access denied\n";foreach([$file,$csv,$xlsx,$cookie] as $p)if(is_file($p))unlink($p);
