<?php
namespace Srms;
/** Additive, resumable conversion. Original core tables and audit snapshots are retained. */
final class AccountKeyMigration {
 private static function exists(string $table): bool {return (bool)Database::scalar('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=? AND table_name=?',[config('db_name'),$table]);}
 private static function has(string $table,string $column): bool {return (bool)Database::scalar('SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=? AND table_name=? AND column_name=?',[config('db_name'),$table,$column]);}
 private static function put(string $table,array $row): void {$cols=array_keys($row);Database::query('INSERT INTO '.$table.' (`'.implode('`,`',$cols).'`) VALUES ('.implode(',',array_fill(0,count($cols),'?')).')',array_values($row));}
 private static function foreign(string $table): void {
  $name='fk_'.$table.'_canonical_account';if(!Database::scalar('SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=? AND table_name=? AND constraint_name=?',[config('db_name'),$table,$name]))Database::query("ALTER TABLE $table ADD CONSTRAINT $name FOREIGN KEY (account_number) REFERENCES parcel_accounts(account_number)");
 }
 public static function run(bool $dry=false): array {
  if(Database::scalar("SELECT COUNT(*) FROM schema_migrations WHERE version='005_permanent_accounts'"))return ['status'=>'already migrated'];
  $sources=[];$keys=[];$records=[];
  foreach(['parcels','properties','accounts'] as $type){$table=self::exists('legacy_'.$type.'_005')?'legacy_'.$type.'_005':$type;$sources[$type]=$table;}
  $parcels=Database::all('SELECT * FROM '.$sources['parcels']);$properties=Database::all('SELECT * FROM '.$sources['properties']);$accounts=Database::all('SELECT * FROM '.$sources['accounts']);
  foreach($parcels as $p){$n=AccountNumber::validate($p['parcel_number']);if($n!==$p['parcel_number'])throw new \DomainException('An existing issued number is not canonical; migration will not renumber it.');$keys['parcels'][$p['id']]=$n;$records[$n]=['account_number'=>$n,'spatial_layer_id'=>$p['spatial_layer_id'],'locality'=>$p['locality'],'zoning'=>$p['zoning'],'status'=>$p['status'],'latitude'=>$p['latitude'],'longitude'=>$p['longitude'],'boundary_geojson'=>$p['boundary_geojson'],'notes'=>$p['notes'],'opened_on'=>substr($p['created_at'],0,10),'created_at'=>$p['created_at'],'updated_at'=>$p['updated_at']];}
  foreach($properties as $p){$n=AccountNumber::validate($p['property_number']);if($n!==$p['property_number']||($p['parcel_id']&&($keys['parcels'][$p['parcel_id']]??null)!==$n))throw new \DomainException('Property and parcel identifiers disagree. Resolve before migration; issued numbers cannot change.');$keys['properties'][$p['id']]=$n;$r=$records[$n]??['account_number'=>$n,'opened_on'=>substr($p['created_at'],0,10),'created_at'=>$p['created_at']];foreach(['land_id','plot_size','plot_size_unit','land_description','property_type','address_line','digital_address','status','assessed_ground_rent','assessment_currency','is_exempt','exemption_reason','updated_at'] as $field)$r[$field]=$p[$field]??null;if($p['locality'])$r['locality']=$p['locality'];if($p['notes']&&$p['notes']!==($r['notes']??null))$r['notes']=trim(($r['notes']??'')."\n".$p['notes']);$records[$n]=$r;}
  $seen=[];foreach($accounts as $a){$n=$keys['properties'][$a['property_id']]??throw new \DomainException('Account has no mapped parcel.');if($a['account_number']!==$n)throw new \DomainException('Existing financial Account number differs from parcel number; migration will not renumber it.');if(isset($seen[$n]))throw new \DomainException('Multiple financial accounts need manual reconciliation before migration.');$seen[$n]=true;$keys['accounts'][$a['id']]=$n;foreach(['primary_ratepayer_id','credit_amount','opened_on','closed_on'] as $f)$records[$n][$f]=$a[$f];}
  $children=['property_ratepayers'=>['property_id'=>'properties'],'ownership_history'=>['property_id'=>'properties'],'property_photos'=>['property_id'=>'properties'],'ground_rent_assessments'=>['property_id'=>'properties'],'ground_rent_bills'=>['account_id'=>'accounts'],'payments'=>['account_id'=>'accounts'],'correspondence'=>['account_id'=>'accounts','property_id'=>'properties']];
  $childNumbers=[];foreach($children as $table=>$columns){foreach(Database::all('SELECT * FROM '.$table) as $row){$numbers=[];foreach($columns as $col=>$type){$old=$row[$col]??$row['legacy_'.$col]??null;if($old)$numbers[]=$keys[$type][$old]??throw new \DomainException("Unmapped reference in $table.");}$numbers=array_unique($numbers);if(count($numbers)!==1)throw new \DomainException("Ambiguous parcel reference in $table.");$childNumbers[$table][$row['id']]=reset($numbers);}}
  $docNumbers=[];$links=Database::all('SELECT * FROM document_links');foreach($links as $l){$type=$l['entity_type'];$n=isset($keys[$type])?($keys[$type][$l['entity_id']]??null):($childNumbers[$type][$l['entity_id']]??null);if(!$n&&self::exists('parcel_accounts'))$n=$l['account_number']??null;if(!$n)throw new \DomainException('A document link has no single parcel Account number. Assign its parcel before migrating.');$docNumbers[$l['document_id']][$n]=true;}
  foreach(Database::all('SELECT id FROM documents') as $d)if(count($docNumbers[$d['id']]??[])!==1)throw new \DomainException('Each existing document must resolve to one parcel before migrating.');
  if(Database::scalar("SELECT COUNT(*) FROM import_batches WHERE entity_type IN ('properties','accounts','parcels') AND status<>'completed'"))throw new \DomainException('Complete or resolve old-style register import batches before migration.');
  $summary=['status'=>'validated','parcels'=>count($records),'legacy_identifiers'=>array_sum(array_map('count',$keys)),'documents'=>count($docNumbers)];if($dry)return $summary;
  Database::query("CREATE TABLE IF NOT EXISTS parcel_accounts (account_number CHAR(12) COLLATE utf8mb4_bin NOT NULL PRIMARY KEY, division_code CHAR(2) GENERATED ALWAYS AS (SUBSTRING(account_number,5,2)) STORED, block_code CHAR(3) GENERATED ALWAYS AS (SUBSTRING(account_number,7,3)) STORED, parcel_code CHAR(3) GENERATED ALWAYS AS (SUBSTRING(account_number,10,3)) STORED, spatial_layer_id CHAR(36) NULL, land_id VARCHAR(120) NULL UNIQUE, locality VARCHAR(150) NULL, zoning VARCHAR(120) NULL, status VARCHAR(30) NOT NULL DEFAULT 'active', latitude DECIMAL(10,7) NULL, longitude DECIMAL(10,7) NULL, boundary_geojson LONGTEXT NULL, plot_size DECIMAL(19,4) NULL, plot_size_unit VARCHAR(30) NULL, land_description VARCHAR(500) NULL, property_type VARCHAR(80) NULL, address_line VARCHAR(255) NULL, digital_address VARCHAR(120) NULL, assessed_ground_rent DECIMAL(19,4) NULL, assessment_currency CHAR(3) NOT NULL DEFAULT 'GHS', is_exempt TINYINT NOT NULL DEFAULT 0, exemption_reason VARCHAR(500) NULL, primary_ratepayer_id CHAR(36) NULL, credit_amount DECIMAL(19,4) NOT NULL DEFAULT 0, opened_on DATE NOT NULL, closed_on DATE NULL, notes TEXT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), FOREIGN KEY(spatial_layer_id) REFERENCES spatial_layers(id), FOREIGN KEY(primary_ratepayer_id) REFERENCES ratepayers(id), INDEX ix_parcel_division_block(division_code,block_code), CONSTRAINT ck_account_format CHECK(account_number REGEXP BINARY '^EDDT[0-9]{8}$')) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  Database::query('CREATE TABLE IF NOT EXISTS legacy_account_keys (entity_type VARCHAR(30) NOT NULL,legacy_id CHAR(36) NOT NULL,account_number CHAR(12) COLLATE utf8mb4_bin NOT NULL,PRIMARY KEY(entity_type,legacy_id),FOREIGN KEY(account_number) REFERENCES parcel_accounts(account_number)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
  Database::transaction(function()use($records,$keys){foreach($records as $n=>$row)if(!Database::scalar('SELECT COUNT(*) FROM parcel_accounts WHERE account_number=?',[$n]))self::put('parcel_accounts',$row);foreach($keys as $type=>$map)foreach($map as $old=>$n)if(!Database::scalar('SELECT COUNT(*) FROM legacy_account_keys WHERE entity_type=? AND legacy_id=?',[$type,$old]))self::put('legacy_account_keys',['entity_type'=>$type,'legacy_id'=>$old,'account_number'=>$n]);});
  foreach($children as $table=>$columns){
   if(!self::has($table,'account_number'))Database::query("ALTER TABLE $table ADD account_number CHAR(12) COLLATE utf8mb4_bin NULL");
   foreach($childNumbers[$table]??[] as $id=>$n)Database::query("UPDATE $table SET account_number=? WHERE id=?",[$n,$id]);
   foreach($columns as $col=>$type){if(self::has($table,$col)){
    $fks=Database::all('SELECT DISTINCT CONSTRAINT_NAME FROM information_schema.key_column_usage WHERE TABLE_SCHEMA=? AND TABLE_NAME=? AND COLUMN_NAME=? AND REFERENCED_TABLE_NAME IS NOT NULL',[config('db_name'),$table,$col]);foreach($fks as $fk)Database::query("ALTER TABLE $table DROP FOREIGN KEY `".$fk['CONSTRAINT_NAME'].'`');
    Database::query("ALTER TABLE $table CHANGE $col legacy_$col CHAR(36) NULL");
   }}
   Database::query("ALTER TABLE $table MODIFY account_number CHAR(12) COLLATE utf8mb4_bin NOT NULL");self::foreign($table);
  }
  foreach(['ground_rent_bills'=>'billing_year','ground_rent_assessments'=>'assessment_year'] as $table=>$year){$name='uq_'.$table.'_canonical_year';if(!Database::scalar('SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=? AND table_name=? AND index_name=?',[config('db_name'),$table,$name]))Database::query("ALTER TABLE $table ADD UNIQUE $name(account_number,$year)");}
  foreach(['documents','document_links'] as $table){if(!self::has($table,'account_number'))Database::query("ALTER TABLE $table ADD account_number CHAR(12) COLLATE utf8mb4_bin NULL");}
  foreach($docNumbers as $id=>$numbers){$n=array_key_first($numbers);Database::query('UPDATE documents SET account_number=? WHERE id=?',[$n,$id]);Database::query('UPDATE document_links SET account_number=? WHERE document_id=?',[$n,$id]);}
  foreach($links as $l)if(isset($keys[$l['entity_type']][$l['entity_id']]))Database::query('UPDATE document_links SET entity_id=? WHERE id=?',[$keys[$l['entity_type']][$l['entity_id']],$l['id']]);
  foreach(['documents','document_links'] as $table){Database::query("ALTER TABLE $table MODIFY account_number CHAR(12) COLLATE utf8mb4_bin NOT NULL");self::foreign($table);}
  foreach($sources as $type=>$source){if($source===$type)Database::query("RENAME TABLE $type TO legacy_{$type}_005");Database::query("CREATE OR REPLACE ALGORITHM=MERGE VIEW $type AS SELECT a.*,a.account_number AS id,a.account_number AS property_number,a.account_number AS parcel_number,a.account_number AS parcel_id,a.account_number AS land_account_number FROM parcel_accounts a");}
  foreach(['insert'=>"BEFORE INSERT ON parcel_accounts FOR EACH ROW BEGIN IF NEW.account_number NOT REGEXP BINARY '^EDDT[0-9]{8}$' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Invalid Account number'; END IF; END",'update'=>"BEFORE UPDATE ON parcel_accounts FOR EACH ROW BEGIN IF BINARY NEW.account_number <> BINARY OLD.account_number THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Account numbers are permanent and cannot be changed'; END IF; END",'delete'=>"BEFORE DELETE ON parcel_accounts FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Issued Account numbers cannot be deleted or reused; archive the parcel'"] as $kind=>$body){$name='permanent_account_'.$kind;if(!Database::scalar('SELECT COUNT(*) FROM information_schema.triggers WHERE trigger_schema=? AND trigger_name=?',[config('db_name'),$name]))Database::query('CREATE TRIGGER '.$name.' '.$body);}
  Database::query("INSERT INTO schema_migrations VALUES ('005_permanent_accounts',CURRENT_TIMESTAMP)");return $summary+['migrated'=>true];
 }
}