<?php
namespace Srms;
final class Backup {
 public static function create(string $destination): string {
  $tables=['roles','phone_identities','ratepayers','users','spatial_layers','parcel_accounts','property_ratepayers','ownership_history','documents','document_links','property_photos','ground_rent_assessments','ground_rent_bills','payments','payment_allocations','financial_adjustments','correspondence','correspondence_events','correspondence_batches','correspondence_batch_items','ratepayer_phone_numbers','user_phone_numbers','import_batches','import_rows','audit_logs','settings','schema_migrations'];
  if(Database::scalar("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=? AND table_name='legacy_account_keys'",[config('db_name')]))$tables[]='legacy_account_keys';$zip=new \ZipArchive();if($zip->open($destination,\ZipArchive::CREATE|\ZipArchive::OVERWRITE)!==true)throw new \RuntimeException('Cannot create export.');$manifest=['format'=>'eddt-trust-export-1','created_at'=>date('c'),'files'=>[]];
  try{Database::transaction(function()use($tables,$zip,&$manifest){foreach($tables as $table){$rows=Database::all('SELECT * FROM '.$table);if($table==='users')foreach($rows as &$r){unset($r['password_hash']);}unset($r);$bytes=json_encode($rows,JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR);$path='data/'.$table.'.json';$zip->addFromString($path,$bytes);$manifest['files'][$path]=hash('sha256',$bytes);}foreach(Database::all('SELECT * FROM documents') as $d){$path=(new LocalStorage())->path($d['storage_key']);if(!is_file($path)||hash_file('sha256',$path)!==$d['sha256_hash'])throw new \RuntimeException('Document integrity failure: '.$d['id']);$name='documents/'.$d['storage_key'];$zip->addFile($path,$name);$manifest['files'][$name]=$d['sha256_hash'];}foreach(Database::all('SELECT id FROM correspondence ORDER BY id') as $c){$out=CorrespondenceOutput::output($c['id'],'download',uuid());$name='correspondence/'.$c['id'].'.pdf';$zip->addFromString($name,$out['bytes']);$manifest['files'][$name]=hash('sha256',$out['bytes']);}foreach(['correspondence_events','audit_logs'] as $table){$bytes=json_encode(Database::all('SELECT * FROM '.$table),JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR);$path='data/'.$table.'.json';$zip->addFromString($path,$bytes);$manifest['files'][$path]=hash('sha256',$bytes);}foreach(glob(SRMS_ROOT.'/app/views/letters/v*.php') as $file){$name='templates/'.basename($file);$zip->addFile($file,$name);$manifest['files'][$name]=hash_file('sha256',$file);}foreach(glob(SRMS_ROOT.'/app/assets/letters/v*/*.png') as $file){$name='templates/assets/'.basename(dirname($file)).'/'.basename($file);$zip->addFile($file,$name);$manifest['files'][$name]=hash_file('sha256',$file);}});$zip->addFromString('manifest.json',json_encode($manifest,JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR));$zip->addFromString('README.txt',"Trust data export. Password hashes and session data are excluded. Use operational database backups for disaster recovery. SHA-256 hashes in manifest.json cover every data/document file.\n");if(!$zip->close())throw new \RuntimeException('Could not finalize export.');return $destination;}catch(\Throwable $e){$zip->close();if(is_file($destination))unlink($destination);throw $e;}
 }
 public static function download(): never {Auth::admin();$dir=SRMS_ROOT.'/var/exports';if(!is_dir($dir))mkdir($dir,0700,true);$path=$dir.'/'.uuid().'.zip';self::create($path);Audit::log('trust_data_export','system');header('Content-Type: application/zip');header('Content-Disposition: attachment; filename="eddt-trust-export-'.today().'.zip"');header('Content-Length: '.filesize($path));try{readfile($path);}finally{unlink($path);}exit;}
}

