<?php
namespace Srms;
final class Correspondence {
 public static function pdf(string $html,array|string $paper='A4'): string {if(!class_exists(\Dompdf\Dompdf::class))throw new \RuntimeException('PDF dependencies are not installed. Run Composer install.');$o=new \Dompdf\Options();$o->set('isRemoteEnabled',false);$o->set('isPhpEnabled',false);$o->set('chroot',config('storage_path'));$pdf=new \Dompdf\Dompdf($o);$pdf->loadHtml($html);$pdf->setPaper($paper);$pdf->render();return $pdf->output();}
 public static function generate(array $d): string {Auth::staff();return Database::transaction(function()use($d){Auth::account(require_value($d,'account_number'));Database::lock('accounts',$d['account_number']);return self::generateLocked($d);});}
 private static function generateLocked(array $d): string {Auth::staff();$type=require_value($d,'type');if(!in_array($type,['demand_notice','invitation','receipt'],true))throw new \DomainException('Invalid correspondence type.');$account=Auth::account(require_value($d,'account_number'));$property=Database::one('SELECT * FROM properties WHERE id=?',[$account['account_number']]);$owner=$account['primary_ratepayer_id']?Database::one('SELECT * FROM ratepayers WHERE id=?',[$account['primary_ratepayer_id']]):null;$bill=null;$payment=null;if($type==='receipt'){$payment=Database::one('SELECT * FROM payments WHERE id=? AND account_number=?',[$d['payment_id']??'',$account['id']])??throw new \DomainException('Select a payment on this account.');}if($type==='demand_notice'){$bill=Database::one('SELECT * FROM ground_rent_bills WHERE id=? AND account_number=?',[$d['bill_id']??'',$account['id']])??throw new \DomainException('Select a bill on this account.');}
  $rows=Database::all('SELECT * FROM ground_rent_bills WHERE account_number=? ORDER BY billing_year',[$account['id']]);$current='0';$arrears='0';$year=$bill['billing_year']??date('Y');foreach($rows as $b){$balance=Money::sub(Money::add(Money::add($b['principal_amount'],$b['penalty_amount']),$b['adjustment_amount']),$b['paid_amount']);if($b['billing_year']<$year)$arrears=Money::add($arrears,$balance);elseif($b['billing_year']==$year)$current=Money::add($current,$balance);}
  $ref=Settings::number('DOC');$settings=Settings::all();$from=empty($d['period_from'])?null:valid_date($d['period_from']);$to=empty($d['period_to'])?null:valid_date($d['period_to']);if($type==='invitation'&&(!$from||!$to||$from>$to))throw new \DomainException('Enter a valid invitation period.');
  $vars=['account'=>$account,'property'=>$property,'owner'=>$owner,'bill'=>$bill,'payment'=>$payment,'current'=>$current,'arrears'=>$arrears,'total'=>Money::add($current,$arrears),'settings'=>$settings,'reference'=>$ref,'printed'=>empty($d['printed_date'])?today():valid_date($d['printed_date']),'period_from'=>$from,'period_to'=>$to,'template_version'=>'2'];
  $photo=Database::one('SELECT d.* FROM property_photos p JOIN documents d ON d.id=p.document_id WHERE p.account_number=? AND p.is_primary=1 AND d.owner_visible=1 AND d.is_current_version=1',[$property['id']]);
if($photo){$path=(new LocalStorage())->path($photo['storage_key']);if(!is_file($path)||!hash_equals($photo['sha256_hash'],hash_file('sha256',$path)))throw new \RuntimeException('The selected photograph is missing or failed integrity verification.');}
$vars['photo_document_id']=$photo['id']??null;$vars['photo_sha256']=$photo['sha256_hash']??null;$vars['qr_target']=url('detail',['type'=>'accounts','id'=>$account['id']]);
  $vars['template_version']='3';$vars['template_sha256']=hash_file('sha256',SRMS_ROOT.'/app/views/letters/v3.php');$vars['asset_hashes']=[];foreach(['letter-logo.png','letter-watermark.png'] as $asset)$vars['asset_hashes'][$asset]=hash_file('sha256',SRMS_ROOT.'/app/assets/letters/v3/'.$asset);
  $json=json_encode($vars,JSON_THROW_ON_ERROR);
  $id=Database::insert('correspondence',['correspondence_type'=>$type,'account_number'=>$account['id'],'ratepayer_id'=>$owner['id']??null,'bill_id'=>$bill['id']??null,'payment_id'=>$payment['id']??null,'reference_number'=>$ref,'printed_at'=>$vars['printed'].' '.date('H:i:s'),'period_from'=>$from,'period_to'=>$to,'subject'=>ucwords(str_replace('_',' ',$type)),'content_variables_json'=>$json,'snapshot_sha256'=>hash('sha256',$json),'generated_document_id'=>null,'created_by'=>Auth::user()['id'],'owner_visible'=>array_key_exists('visibility_submitted',$d)?(int)!empty($d['owner_visible']):1,'template_version'=>'3']);
  Audit::log('correspondence_created','correspondence',$id,null,['account_number'=>$account['id']]);return $id;
 }
}

