<?php
namespace Srms;
final class DashboardRepository {
 public static function data(array $filters=[]): array {
  [$scope,$params]=Reports::scope();$properties=PropertyPayments::rows();$counts=array_fill_keys(array_keys(PropertyPayments::LABELS),0);$outstanding='0';$billed='0';$paid='0';
  foreach($properties as $p){$counts[$p['payment_status']]++;$outstanding=Money::add($outstanding,$p['outstanding']);$billed=Money::add($billed,(string)$p['billed']);$paid=Money::add($paid,(string)$p['paid']);}
  $accounts=Database::one("SELECT COUNT(*) account_count,COALESCE(SUM(a.credit_amount),0) credit FROM accounts a JOIN properties p ON p.id=a.account_number WHERE $scope",$params);
  $collected=(string)Database::scalar("SELECT COALESCE(SUM(pay.amount),0) FROM payments pay JOIN accounts a ON a.id=pay.account_number JOIN properties p ON p.id=a.account_number WHERE $scope AND pay.status='posted'",$params);
  $year=isset($filters['year'])?filter_var($filters['year'],FILTER_VALIDATE_INT):null;if($year!==null&&($year===false||$year<1900||$year>2200))throw new \DomainException('Select a year between 1900 and 2200.');$start=$year?new \DateTimeImmutable($year.'-01-01'):(new \DateTimeImmutable('first day of this month'))->modify('-11 months');$end=$year?$start->modify('+1 year'):(new \DateTimeImmutable('first day of next month'));$monthly=[];
  for($n=0;$n<12;$n++){$date=$start->modify("+$n months");$monthly[$date->format('Y-m')]=['month'=>$date->format('Y-m'),'label'=>$date->format('M'),'full_label'=>$date->format('M Y'),'amount'=>'0.0000'];}
  $methods=['cash'=>['label'=>'Cash','amount'=>'0.0000'],'bank'=>['label'=>'Bank transfer','amount'=>'0.0000'],'cheque'=>['label'=>'Cheque','amount'=>'0.0000'],'mobile_money'=>['label'=>'Mobile money','amount'=>'0.0000']];
  $payments=Database::all("SELECT YEAR(pay.payment_date) payment_year,MONTH(pay.payment_date) payment_month,pay.payment_method,SUM(pay.amount) amount FROM payments pay JOIN accounts a ON a.id=pay.account_number JOIN properties p ON p.id=a.account_number WHERE $scope AND pay.status='posted' AND pay.payment_date>=? AND pay.payment_date<? GROUP BY YEAR(pay.payment_date),MONTH(pay.payment_date),pay.payment_method",[...$params,$start->format('Y-m-d'),$end->format('Y-m-d')]);
  foreach($payments as $r){$key=sprintf('%04d-%02d',$r['payment_year'],$r['payment_month']);$monthly[$key]['amount']=Money::add($monthly[$key]['amount'],$r['amount']);$methods[$r['payment_method']]['amount']=Money::add($methods[$r['payment_method']]['amount'],$r['amount']);}
  $years=Database::all(Database::page("SELECT b.billing_year,SUM(b.principal_amount+b.penalty_amount+b.adjustment_amount) billed,SUM(b.paid_amount) paid,SUM(b.principal_amount+b.penalty_amount+b.adjustment_amount-b.paid_amount) outstanding FROM ground_rent_bills b JOIN accounts a ON a.id=b.account_number JOIN properties p ON p.id=a.account_number WHERE $scope GROUP BY b.billing_year ORDER BY b.billing_year DESC",1,5),$params);
  $recent=Database::all(Database::page("SELECT pay.receipt_number,a.account_number,pay.payment_date,pay.amount,pay.payment_method,pay.status FROM payments pay JOIN accounts a ON a.id=pay.account_number JOIN properties p ON p.id=a.account_number WHERE $scope ORDER BY pay.payment_date DESC,pay.created_at DESC,pay.id",1,6),$params);
  return ['selected_year'=>$year,'property_count'=>count($properties),'account_count'=>(int)$accounts['account_count'],'collected'=>$collected,'outstanding'=>$outstanding,'credit'=>$accounts['credit'],'billed'=>$billed,'paid'=>$paid,'statuses'=>$counts,'monthly'=>array_values($monthly),'methods'=>array_values(array_map(fn($key,$value)=>['key'=>$key]+$value,array_keys($methods),$methods)),'years'=>array_reverse($years),'recent'=>$recent,'period'=>$start->format('M Y').' to '.$end->modify('-1 month')->format('M Y')];
 }
}