<?php
namespace Srms;
use DomainException;
final class Documents {
 public static function accountForEntity(string $type,string $id):string {
  if(in_array($type,['parcels','properties','accounts'],true)){$number=AccountNumber::validate($id);Auth::property($number);return $number;}
  if(in_array($type,['ground_rent_bills','payments'],true)){$r=Database::one('SELECT account_number FROM '.$type.' WHERE id=?',[$id])??throw new DomainException('Record not found.');Auth::property($r['account_number']);return $r['account_number'];}
  throw new DomainException('Every document must be linked to a parcel Account number, bill or payment.');
 }
 public static function authorizeEntity(string $type,string $id):void {self::accountForEntity($type,$id);}
 public static function allowed(array $doc):bool {if(!Auth::user())return false;if(!Auth::owner())return true;if(!$doc['owner_visible'])return false;try{Auth::property($doc['account_number']);return true;}catch(DomainException){return false;}}
 public static function store(string $bytes,string $name,string $type,string $entity,string $id,bool $visible=false,?string $previous=null): string {
  Auth::staff();self::authorizeEntity($entity,$id);$mime=(new \finfo(FILEINFO_MIME_TYPE))->buffer($bytes);$ext=['application/pdf'=>'pdf','image/jpeg'=>'jpg','image/png'=>'png'][$mime]??throw new DomainException('Only PDF, JPEG and PNG files are accepted.');if(strlen($bytes)>(int)Settings::get('upload_mb','15')*1024*1024)throw new DomainException('File exceeds the configured upload limit.');if($ext!=='pdf'){ $info=getimagesizefromstring($bytes);if(!$info||$info[0]*$info[1]>40000000)throw new DomainException('Invalid or excessively large image.');}
  $key=uuid().'.'.$ext;$storage=new LocalStorage();$storage->put($key,$bytes);
  try{return Database::transaction(function()use($key,$bytes,$name,$type,$entity,$id,$visible,$previous,$mime){$group=uuid();$version=1;if($previous){$old=Database::lock('documents',$previous);if(!$old['is_current_version'])throw new DomainException('Select the current document version.');if(!Database::one('SELECT id FROM document_links WHERE document_id=? AND entity_type=? AND entity_id=?',[$previous,$entity,$id]))throw new DomainException('Version must retain its original record link.');$group=$old['version_group_id']?:$old['id'];$version=(int)$old['version_number']+1;Database::update('documents',$previous,['is_current_version'=>0]);}
   $doc=Database::insert('documents',['account_number'=>self::accountForEntity($entity,$id),'original_filename'=>substr(basename($name),0,255),'storage_key'=>$key,'mime_type'=>$mime,'file_size_bytes'=>strlen($bytes),'sha256_hash'=>hash('sha256',$bytes),'document_type'=>$type,'version_group_id'=>$group,'previous_version_id'=>$previous,'version_number'=>$version,'owner_visible'=>$visible?1:0,'uploaded_by'=>Auth::user()['id']]);Database::insert('document_links',['account_number'=>self::accountForEntity($entity,$id),'document_id'=>$doc,'entity_type'=>$entity,'entity_id'=>$id]);Audit::log('document_created','documents',$doc,null,['filename'=>$name,'version'=>$version]);return $doc;});}catch(\Throwable $e){unlink($storage->path($key));throw $e;}
 }
 public static function upload(array $file,array $d): string {Auth::staff();if(!empty($d['taken_at']))valid_date($d['taken_at']);if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||!is_uploaded_file($file['tmp_name']))throw new DomainException('Choose a file within the server upload limit.');$bytes=file_get_contents($file['tmp_name']);$entity=require_value($d,'entity_type');$id=require_value($d,'entity_id');$photo=!empty($d['photo']);if($photo&&(!in_array($entity,['parcels','properties','accounts'],true)||!str_starts_with((new \finfo(FILEINFO_MIME_TYPE))->buffer($bytes),'image/')))throw new DomainException('Property photos must be images linked to a property.');$doc=self::store($bytes,$file['name'],$photo?'property_photo':($d['document_type']??'attachment'),$entity,$id,!empty($d['owner_visible']),trim($d['previous_version_id']??'')?:null);if($photo)Database::transaction(function()use($doc,$id,$d){Database::lock('properties',$id);$primary=!empty($d['is_primary'])?1:0;if($primary)Database::query('UPDATE property_photos SET is_primary=0 WHERE account_number=?',[$id]);Database::insert('property_photos',['account_number'=>$id,'document_id'=>$doc,'caption'=>$d['caption']??null,'taken_at'=>empty($d['taken_at'])?null:valid_date($d['taken_at']).' 00:00:00','display_order'=>(int)($d['display_order']??0),'is_primary'=>$primary,'created_by'=>Auth::user()['id']]);});return $doc;}
 public static function download(string $id,bool $inline=false): never {$doc=Database::one('SELECT * FROM documents WHERE id=?',[$id])??throw new DomainException('Document not found.');if(!self::allowed($doc))throw new DomainException('Access denied.');$path=(new LocalStorage())->path($doc['storage_key']);if(!is_file($path)||!hash_equals($doc['sha256_hash'],hash_file('sha256',$path)))throw new \RuntimeException('Document is missing or failed integrity verification.');Audit::log('document_downloaded','documents',$id);header('Content-Type: '.$doc['mime_type']);header('Content-Length: '.filesize($path));header('Content-Disposition: '.($inline?'inline':'attachment').'; filename="'.preg_replace('/[^a-zA-Z0-9._-]/','_',$doc['original_filename']).'"');header("Content-Security-Policy: sandbox");readfile($path);exit;}
 public static function photo(array $d): void {Auth::staff();$id=require_value($d,'id');Database::transaction(function()use($id,$d){$p=Database::one('SELECT * FROM property_photos WHERE id=?',[$id])??throw new DomainException('Photo not found.');Database::lock('properties',$p['account_number']);if(!empty($d['is_primary']))Database::query('UPDATE property_photos SET is_primary=0 WHERE account_number=?',[$p['account_number']]);Database::update('property_photos',$id,['caption'=>$d['caption']??'','display_order'=>(int)($d['display_order']??0),'is_primary'=>empty($d['is_primary'])?0:1,'taken_at'=>empty($d['taken_at'])?null:valid_date($d['taken_at']).' 00:00:00']);Audit::log('photo_updated','properties',$p['account_number']);});}
}
