<?php
namespace Srms;
use DomainException;
final class Finance {
 private static function requireOwner(string $number):void {if(!Database::scalar("SELECT COUNT(*) FROM property_ratepayers WHERE account_number=? AND relationship_type='owner' AND start_date<=? AND (end_date IS NULL OR end_date>?)",[$number,today(),today()]))throw new DomainException('An Administrator must assign an owner before rent can be assessed, approved or billed.');}
 public static function assessment(array $d): string {Auth::staff();$property=require_value($d,'account_number');Auth::property($property);$year=(int)require_value($d,'assessment_year');if($year<1900||$year>2200)throw new DomainException('Invalid assessment year.');$amount=Money::parse(require_value($d,'annual_amount'));if(Money::cmp($amount,'0')<=0)throw new DomainException('Assessment must be positive.');return Database::transaction(function()use($property,$year,$amount,$d){Database::lock('properties',$property);self::requireOwner($property);$id=Database::insert('ground_rent_assessments',['account_number'=>$property,'assessment_year'=>$year,'annual_amount'=>$amount,'currency'=>'GHS','effective_from'=>"$year-01-01",'effective_to'=>"$year-12-31",'status'=>'pending','notes'=>$d['notes']??null]);Audit::log('assessment_created','ground_rent_assessments',$id,null,['amount'=>$amount,'year'=>$year]);return $id;});}
 public static function approve(string $id): void {Auth::admin();Database::transaction(function()use($id){$a=Database::lock('ground_rent_assessments',$id);self::requireOwner($a['account_number']);if($a['status']!=='pending')throw new DomainException('Only pending assessments can be approved.');Database::update('ground_rent_assessments',$id,['status'=>'approved','approved_by'=>Auth::user()['id'],'approved_at'=>date('Y-m-d H:i:s')]);Audit::log('assessment_approved','ground_rent_assessments',$id);});}
 public static function issue(string $assessmentId,string $due): string {Auth::staff();valid_date($due);return Database::transaction(function()use($assessmentId,$due){$a=Database::one('SELECT * FROM ground_rent_assessments WHERE id=?',[$assessmentId])??throw new DomainException('Assessment not found.');if($a['status']!=='approved')throw new DomainException('Administrator approval is required.');$property=Database::lock('properties',$a['account_number']);$account=Database::one("SELECT * FROM accounts WHERE account_number=? AND status='active'",[$a['account_number']])??throw new DomainException('Property needs an active land account.');Database::lock('accounts',$account['id']);$existing=Database::one('SELECT id FROM ground_rent_bills WHERE account_number=? AND billing_year=?',[$account['id'],$a['assessment_year']]);if($existing)return $existing['id'];if($property['is_exempt'])throw new DomainException('This property is exempt. An Administrator must remove the exemption before a new bill can be issued.');$id=Database::insert('ground_rent_bills',['bill_number'=>Settings::number('BILL'),'account_number'=>$account['id'],'assessment_id'=>$assessmentId,'billing_year'=>$a['assessment_year'],'issue_date'=>today(),'due_date'=>$due,'payment_deadline'=>$due,'principal_amount'=>$a['annual_amount'],'currency'=>'GHS','created_by'=>Auth::user()['id']]);self::reconcile($account['id']);Audit::log('bill_issued','ground_rent_bills',$id,null,['assessment_id'=>$assessmentId]);return $id;});}
 public static function batch(int $year,string $due): int {Auth::staff();valid_date($due);$rows=Database::all("SELECT g.id FROM ground_rent_assessments g JOIN properties p ON p.id=g.account_number WHERE g.assessment_year=? AND g.status='approved' AND p.is_exempt=0",[$year]);return Database::transaction(function()use($rows,$due){foreach($rows as $r)self::issue($r['id'],$due);return count($rows);});}
 public static function payment(array $d): string {Auth::staff();$account=require_value($d,'account_number');Auth::account($account);$amount=Money::parse(require_value($d,'amount'));if(Money::cmp($amount,'0')<=0)throw new DomainException('Payment must be greater than zero.');$date=valid_date(require_value($d,'payment_date'));if($date>today())throw new DomainException('Payment date cannot be in the future.');$method=require_value($d,'payment_method');if(!in_array($method,['cash','bank','cheque','mobile_money'],true))throw new DomainException('Invalid payment method.');$key=require_value($d,'request_key');if(!preg_match('/^[a-f0-9-]{36}$/',$key))throw new DomainException('Invalid submission token.');return Database::transaction(function()use($d,$account,$amount,$date,$method,$key){Database::lock('accounts',$account);$old=Database::one('SELECT * FROM payments WHERE request_key=?',[$key]);if($old){if($old['account_number']!==$account||Money::cmp($old['amount'],$amount)!==0)throw new DomainException('Submission token was already used.');return $old['id'];}$id=Database::insert('payments',['receipt_number'=>Settings::number('RCPT'),'account_number'=>$account,'payment_date'=>$date,'amount'=>$amount,'currency'=>'GHS','payment_method'=>$method,'external_reference'=>trim($d['external_reference']??'')?:null,'payer_name'=>trim($d['payer_name']??'')?:null,'notes'=>$d['notes']??null,'recorded_by'=>Auth::user()['id'],'request_key'=>$key]);self::reconcile($account);Audit::log('payment_posted','payments',$id,null,['amount'=>$amount,'account_number'=>$account]);return $id;});}
 public static function reverse(string $id,string $reason): void {Auth::admin();if(trim($reason)==='')throw new DomainException('A reversal reason is required.');Database::transaction(function()use($id,$reason){$p=Database::one('SELECT * FROM payments WHERE id=?',[$id])??throw new DomainException('Payment not found.');Database::lock('accounts',$p['account_number']);$p=Database::lock('payments',$id);if($p['status']!=='posted')throw new DomainException('This payment is already reversed.');Database::update('payments',$id,['status'=>'reversed','reversal_reason'=>$reason,'reversed_by'=>Auth::user()['id'],'reversed_at'=>date('Y-m-d H:i:s')]);self::reconcile($p['account_number']);Audit::log('payment_reversed','payments',$id,$p,['reason'=>$reason]);});}
 public static function adjust(string $bill,string $type,string $amount,string $reason): void {Auth::staff();if(!in_array($type,['penalty','adjustment'],true))throw new DomainException('Invalid adjustment type.');$amount=Money::parse($amount,$type==='adjustment');if(trim($reason)===''||Money::cmp($amount,'0')===0)throw new DomainException('A nonzero amount and reason are required.');Database::transaction(function()use($bill,$type,$amount,$reason){$b=Database::one('SELECT * FROM ground_rent_bills WHERE id=?',[$bill])??throw new DomainException('Bill not found.');Database::lock('accounts',$b['account_number']);$b=Database::lock('ground_rent_bills',$bill);$col=$type==='penalty'?'penalty_amount':'adjustment_amount';$new=Money::add($b[$col],$amount);$total=Money::add(Money::add($b['principal_amount'],$b['penalty_amount']),$b['adjustment_amount']);if(Money::cmp(Money::add($total,$amount),'0')<0)throw new DomainException('Adjustment would make the bill negative.');Database::update('ground_rent_bills',$bill,[$col=>$new]);Database::insert('financial_adjustments',['bill_id'=>$bill,'adjustment_type'=>$type,'amount'=>$amount,'reason'=>$reason,'created_by'=>Auth::user()['id']]);self::reconcile($b['account_number']);Audit::log('bill_adjusted','ground_rent_bills',$bill,$b,['type'=>$type,'amount'=>$amount,'reason'=>$reason]);});}
 // Caller owns the account row lock. Rebuild derived allocations from immutable posted payments.
 public static function reconcile(string $account): void {
  if(!Database::connection()->inTransaction())throw new \LogicException('Reconciliation requires a transaction.');
  $bills=Database::all('SELECT * FROM ground_rent_bills WHERE account_number=? ORDER BY billing_year, due_date, id',[$account]);
  $payments=Database::all("SELECT * FROM payments WHERE account_number=? AND status='posted' ORDER BY payment_date,created_at,id",[$account]);
  Database::query('DELETE FROM payment_allocations WHERE payment_id IN (SELECT id FROM payments WHERE account_number=?)',[$account]);
  $remaining=[];foreach($bills as $b)$remaining[$b['id']]=Money::add(Money::add($b['principal_amount'],$b['penalty_amount']),$b['adjustment_amount']);
  $credit='0.0000';foreach($payments as $p){$left=$p['amount'];foreach($bills as $b){if(Money::cmp($left,'0')<=0)break;$n=Money::min($remaining[$b['id']],$left);if(Money::cmp($n,'0')>0){Database::insert('payment_allocations',['payment_id'=>$p['id'],'bill_id'=>$b['id'],'amount'=>$n]);$remaining[$b['id']]=Money::sub($remaining[$b['id']],$n);$left=Money::sub($left,$n);}}$credit=Money::add($credit,$left);}
  foreach($bills as $b){$total=Money::add(Money::add($b['principal_amount'],$b['penalty_amount']),$b['adjustment_amount']);$paid=Money::sub($total,$remaining[$b['id']]);Database::update('ground_rent_bills',$b['id'],['paid_amount'=>$paid,'status'=>Money::cmp($remaining[$b['id']],'0')===0?'paid':(Money::cmp($paid,'0')>0?'partial':'issued')]);}
  Database::update('accounts',$account,['credit_amount'=>$credit]);
 }
 public static function opening(array $d): string {Auth::admin();$account=require_value($d,'account_number');$year=(int)require_value($d,'billing_year');$amount=Money::parse(require_value($d,'amount'));if($year<1900||$year>2200||Money::cmp($amount,'0')<=0)throw new DomainException('Invalid opening balance.');return Database::transaction(function()use($account,$year,$amount,$d){Database::lock('accounts',$account);$id=Database::insert('ground_rent_bills',['account_number'=>$account,'bill_number'=>Settings::number('OPEN'),'billing_year'=>$year,'issue_date'=>today(),'due_date'=>valid_date($d['due_date']??"$year-12-31"),'principal_amount'=>$amount,'opening_balance'=>1,'notes'=>require_value($d,'reference'),'created_by'=>Auth::user()['id']]);self::reconcile($account);Audit::log('opening_balance','ground_rent_bills',$id,null,$d);return $id;});}
}
