<?php
namespace Srms;
final class PropertyContactReport {
 public const HEADERS=['account_number','division_code','block_code','parcel_code','locality','property_type','land_id','plot_size','plot_size_unit','address_line','digital_address','property_status','is_exempt','years_assessed','ground_rent_by_year_ghs','report_year','current_year_ground_rent_ghs','arrears_ghs','outstanding_ghs','credit_ghs','owner_number','owner_name','organization','ownership_share_percent','owner_phones','owner_email','owner_postal_address'];
 public static function rows(array $filters=[]): array {
  if(!Auth::user()||Auth::owner())throw new \DomainException('Staff report only.');
  $sql="SELECT p.account_number,p.division_code,p.block_code,p.parcel_code,p.locality,p.property_type,p.land_id,p.plot_size,p.plot_size_unit,p.address_line,p.digital_address,p.status property_status,p.is_exempt,COALESCE(b.arrears,0) arrears_ghs,COALESCE(b.outstanding,0) outstanding_ghs,p.credit_amount credit_ghs,r.ratepayer_number owner_number,r.full_name owner_name,r.organization_name organization,o.ownership_percentage ownership_share_percent,r.id owner_id,r.email owner_email,r.postal_address owner_postal_address FROM parcel_accounts p LEFT JOIN property_ratepayers o ON o.account_number=p.account_number AND o.relationship_type='owner' AND o.start_date<=? AND (o.end_date IS NULL OR o.end_date>?) LEFT JOIN ratepayers r ON r.id=o.ratepayer_id LEFT JOIN (SELECT account_number,SUM(CASE WHEN billing_year<".(int)date('Y')." THEN principal_amount+penalty_amount+adjustment_amount-paid_amount ELSE 0 END) arrears,SUM(principal_amount+penalty_amount+adjustment_amount-paid_amount) outstanding FROM ground_rent_bills GROUP BY account_number) b ON b.account_number=p.account_number WHERE 1=1";
  $params=[today(),today()];foreach(['locality'=>'p.locality','q'=>'p.account_number'] as $key=>$column)if(trim($filters[$key]??'')!==''){$term='%'.str_replace(['!','%','_'],['!!','!%','!_'],mb_substr(trim($filters[$key]),0,100)).'%';if($key==='q'){$sql.=" AND (p.account_number LIKE ? ESCAPE '!' OR r.full_name LIKE ? ESCAPE '!' OR r.organization_name LIKE ? ESCAPE '!')";array_push($params,$term,$term,$term);}else{$sql.=" AND $column LIKE ? ESCAPE '!'";$params[]=$term;}}
  $assessments=[];foreach(Database::all("SELECT account_number,assessment_year,annual_amount FROM ground_rent_assessments WHERE status='approved' ORDER BY account_number,assessment_year") as $a)$assessments[$a['account_number']][$a['assessment_year']]=$a['annual_amount'];
  $phones=[];foreach(Database::all('SELECT ratepayer_id,phone_number FROM ratepayer_phone_numbers ORDER BY is_primary DESC,phone_number') as $p)$phones[$p['ratepayer_id']][]=$p['phone_number'];
  $rows=Database::all($sql.' ORDER BY p.account_number,r.full_name',$params);foreach($rows as &$row){$annual=$assessments[$row['account_number']]??[];$row['years_assessed']=implode('; ',array_keys($annual));$amounts=[];foreach($annual as $year=>$amount)$amounts[]=$year.': '.$amount;$row['ground_rent_by_year_ghs']=implode('; ',$amounts);$row['report_year']=date('Y');$row['current_year_ground_rent_ghs']=$annual[(int)date('Y')]??'';$row['owner_phones']=implode('; ',array_unique($phones[$row['owner_id']]??[]));unset($row['owner_id']);$row=array_replace(array_fill_keys(self::HEADERS,''),$row);}unset($row);return $rows;
 }
 public static function csvCell(mixed $value): string {$v=(string)($value??'');return preg_match('/^[\s]*[=+@-]|^[\t\r\n]/u',$v)?"'".$v:$v;}
}
