<?php
namespace Srms;
use DomainException;
final class Registry {
 public const FIELDS=[
 'parcels'=>['account_number','spatial_layer_id','locality','zoning','land_id','plot_size','plot_size_unit','land_description','property_type','address_line','digital_address','latitude','longitude','boundary_geojson','status','notes'],
 'ratepayers'=>['ratepayer_number','ratepayer_type','full_name','organization_name','company_registration_number','national_id','email','postal_address','status','notes'],
 'spatial_layers'=>['name','layer_type','description','source_reference','display_order','is_visible_by_default','is_active'],
 ];
 public static function normalizeType(string $type): string {
  return match($type){'properties'=>'parcels','property'=>'parcels','accounts'=>'parcels','account'=>'parcels',default=>$type};
 }
 public static function save(string $type,array $d,?string $id=null):string {
  $type=self::normalizeType($type);Auth::staff();if(!isset(self::FIELDS[$type]))throw new DomainException('Use the unified Parcels / Properties register.');$values=[];foreach(self::FIELDS[$type] as $field)if(array_key_exists($field,$d))$values[$field]=trim((string)$d[$field])===''?null:trim((string)$d[$field]);
  if($type==='parcels'){$number=AccountNumber::validate(require_value($d,'account_number'));if($id!==null&&$id!==$number)throw new DomainException('Account numbers are permanent and cannot be changed.');$values['account_number']=$number;if(!$id)$values['opened_on']=today();if(isset($values['plot_size']))$values['plot_size']=Money::parse($values['plot_size']);foreach(['latitude'=>90,'longitude'=>180] as $k=>$limit)if(isset($values[$k])&&(!is_numeric($values[$k])||abs((float)$values[$k])>$limit))throw new DomainException('Invalid '.$k);if(isset($values['boundary_geojson']))$values['boundary_geojson']=self::geometry($values['boundary_geojson']);}
  if(isset($values['status'])&&!in_array($values['status'],['active','archived','closed'],true))throw new DomainException('Invalid status.');
  if($type==='ratepayers'){if(!$id&&empty($values['ratepayer_number']))$values['ratepayer_number']=Settings::number('OWNER');require_value($values,'ratepayer_number');require_value($values,'full_name');if(!in_array($values['ratepayer_type']??'individual',['individual','corporate'],true))throw new DomainException('Invalid owner type.');if(($values['ratepayer_type']??'')==='corporate')require_value($values,'organization_name');if(!empty($values['email'])&&!filter_var($values['email'],FILTER_VALIDATE_EMAIL))throw new DomainException('Invalid email.');}
  if($type==='spatial_layers'){require_value($values,'name');require_value($values,'layer_type');}
  return Database::transaction(function()use($type,$values,$id){$old=$id?Database::lock($type,$id):null;if($id)Database::update($type,$id,$values);else $id=Database::insert($type,$values);Audit::log($old?'record_updated':'record_created',$type,$id,$old,$values);return $id;});
 }
 public static function geometry(string $json): string {$g=json_decode($json,true,64,JSON_THROW_ON_ERROR);if(($g['type']??'')==='Feature')$g=$g['geometry'];if(!in_array($g['type']??'',['Polygon','MultiPolygon','Point'],true))throw new DomainException('Use Point, Polygon or MultiPolygon GeoJSON.');$point=function($p){if(!is_array($p)||count($p)<2||!is_numeric($p[0])||!is_numeric($p[1])||abs((float)$p[0])>180||abs((float)$p[1])>90)throw new DomainException('Invalid GeoJSON coordinates.');};$ring=function($r)use($point){if(!is_array($r)||count($r)<4||$r[0]!==$r[count($r)-1])throw new DomainException('Polygon rings must be closed with at least four coordinates.');foreach($r as $p)$point($p);};$c=$g['coordinates']??[];if($g['type']==='Point')$point($c);else{$polys=$g['type']==='Polygon'?[$c]:$c;if(!$polys)throw new DomainException('Empty geometry.');foreach($polys as $poly){if(!$poly)throw new DomainException('Empty polygon.');foreach($poly as $r)$ring($r);}}return json_encode($g,JSON_THROW_ON_ERROR);}
 public static function ownership(array $d): void {Auth::admin();$property=require_value($d,'account_number');$owner=require_value($d,'ratepayer_id');$date=valid_date(require_value($d,'start_date'));if($date>today())throw new DomainException('Future transfers are not supported; record the transfer when effective.');$share=trim($d['ownership_percentage']??'');if($share!==''&&(!is_numeric($share)||$share<=0||$share>100))throw new DomainException('Ownership share must be between 0 and 100.');Database::transaction(function()use($d,$property,$owner,$date,$share){Database::lock('properties',$property);if(!Database::one("SELECT id FROM ratepayers WHERE id=? AND status='active'",[$owner]))throw new DomainException('Select an active owner.');$previous=trim($d['previous_ratepayer_id']??'');if($previous){$links=Database::all("SELECT * FROM property_ratepayers WHERE account_number=? AND ratepayer_id=? AND relationship_type='owner' AND end_date IS NULL",[$property,$previous]);if(!$links)throw new DomainException('Previous owner has no current ownership.');foreach($links as $link){if($date<$link['start_date'])throw new DomainException('Transfer predates ownership.');Database::update('property_ratepayers',$link['id'],['end_date'=>$date]);}Database::insert('ownership_history',['account_number'=>$property,'previous_ratepayer_id'=>$previous,'new_ratepayer_id'=>$owner,'transfer_date'=>$date,'transfer_reference'=>$d['transfer_reference']??null,'recorded_by'=>Auth::user()['id']]);}
  if(Database::one("SELECT id FROM property_ratepayers WHERE account_number=? AND ratepayer_id=? AND relationship_type='owner' AND (end_date IS NULL OR end_date>?)",[$property,$owner,$date]))throw new DomainException('Overlapping owner relationship.');Database::insert('property_ratepayers',['account_number'=>$property,'ratepayer_id'=>$owner,'relationship_type'=>'owner','ownership_percentage'=>$share?:null,'start_date'=>$date]);Database::query('UPDATE parcel_accounts SET primary_ratepayer_id=? WHERE account_number=? AND (primary_ratepayer_id IS NULL OR primary_ratepayer_id=?)',[$owner,$property,$previous]);Audit::log('ownership_changed','properties',$property,null,$d);});}
 public static function phone(array $d): void {Auth::staff();$ratepayer=require_value($d,'ratepayer_id');$phone=Auth::phone(require_value($d,'phone_number'));$verified=!empty($d['is_verified'])?1:0;$login=!empty($d['can_login'])?1:0;if(($verified||$login)&&Auth::role()!=='Administrator')throw new DomainException('Only Administrators verify phones or enable login.');Database::transaction(function()use($d,$ratepayer,$phone,$verified,$login){Database::lock('ratepayers',$ratepayer);PhoneIdentity::claim($phone,'ratepayer',$ratepayer);if(Database::one('SELECT id FROM user_phone_numbers WHERE phone_number=?',[$phone]))throw new DomainException('Phone already belongs to a staff login.');$existing=Database::one('SELECT * FROM ratepayer_phone_numbers WHERE phone_number=?',[$phone]);if($existing&&$existing['ratepayer_id']!==$ratepayer)throw new DomainException('Phone belongs to another owner.');$primary=!empty($d['is_primary'])?1:0;if($primary)Database::query('UPDATE ratepayer_phone_numbers SET is_primary=0 WHERE ratepayer_id=?',[$ratepayer]);$v=['ratepayer_id'=>$ratepayer,'phone_number'=>$phone,'phone_label'=>$d['phone_label']??null,'is_primary'=>$primary,'is_verified'=>$verified,'can_login'=>$login];if($existing){if(Auth::role()!=='Administrator'){$v['is_verified']=$existing['is_verified'];$v['can_login']=$existing['can_login'];}Database::update('ratepayer_phone_numbers',$existing['id'],$v);}else Database::insert('ratepayer_phone_numbers',$v);Audit::log('phone_updated','ratepayers',$ratepayer,null,$v);});}
}

