<?php
namespace Srms;
final class Reports {
 public const TYPES=['property_contacts'=>'Properties and owner contacts','balances'=>'Account balances','assessments'=>'Assessments','billing'=>'Billing register','collections'=>'Collections','arrears'=>'Outstanding arrears','credits'=>'Account credits','ownership'=>'Ownership register','correspondence'=>'Correspondence and print requests','documents'=>'Document register','audit'=>'Audit activity'];
 public static function scope(string $propertyAlias='p'): array {if(!Auth::owner())return ['1=1',[]];return ["EXISTS (SELECT 1 FROM property_ratepayers access_owner WHERE access_owner.account_number=$propertyAlias.id AND access_owner.ratepayer_id=? AND access_owner.relationship_type='owner' AND access_owner.start_date<=? AND (access_owner.end_date IS NULL OR access_owner.end_date>?))",[Auth::user()['ratepayer_id'],today(),today()]];}
 public static function rows(string $type,array $filters=[]): array {
  if($type==='property_contacts')return PropertyContactReport::rows($filters);
  if(!isset(self::TYPES[$type]))throw new \DomainException('Unknown report.');if(Auth::owner()&&in_array($type,['audit','ownership','documents','assessments'],true))throw new \DomainException('Staff report only.');[$scope,$params]=self::scope();$dateField=null;
  $sql=match($type){
   'balances','credits'=>"SELECT a.account_number, p.property_number, p.land_id, p.locality, COALESCE((SELECT SUM(b.principal_amount+b.penalty_amount+b.adjustment_amount-b.paid_amount) FROM ground_rent_bills b WHERE b.account_number=a.id),0) outstanding, a.credit_amount FROM accounts a JOIN properties p ON p.id=a.account_number WHERE $scope".($type==='credits'?' AND a.credit_amount>0':''),
   'assessments'=>"SELECT p.property_number,p.locality,g.assessment_year,g.annual_amount,g.status,g.approved_at FROM ground_rent_assessments g JOIN properties p ON p.id=g.account_number WHERE $scope",
   'billing','arrears'=>"SELECT b.bill_number,a.account_number,p.property_number,p.locality,b.billing_year,b.issue_date,b.due_date,b.principal_amount,b.penalty_amount,b.adjustment_amount,b.paid_amount,(b.principal_amount+b.penalty_amount+b.adjustment_amount-b.paid_amount) outstanding,b.status FROM ground_rent_bills b JOIN accounts a ON a.id=b.account_number JOIN properties p ON p.id=a.account_number WHERE $scope".($type==='arrears'?' AND b.due_date<? AND b.principal_amount+b.penalty_amount+b.adjustment_amount>b.paid_amount':''),
   'collections'=>"SELECT pay.receipt_number,a.account_number,p.property_number,p.locality,pay.payment_date,pay.amount,pay.payment_method,pay.external_reference,pay.status FROM payments pay JOIN accounts a ON a.id=pay.account_number JOIN properties p ON p.id=a.account_number WHERE $scope",
   'ownership'=>"SELECT p.property_number,p.land_id,p.locality,r.full_name,r.organization_name,o.ownership_percentage,o.start_date,o.end_date FROM property_ratepayers o JOIN properties p ON p.id=o.account_number JOIN ratepayers r ON r.id=o.ratepayer_id WHERE $scope",
   'correspondence'=>"SELECT c.account_number,c.reference_number,c.correspondence_type,c.template_version,c.created_at,u.full_name creator,c.owner_visible,(SELECT COUNT(*) FROM correspondence_events e WHERE e.correspondence_id=c.id AND e.action='print') print_requests,(SELECT MAX(created_at) FROM correspondence_events e WHERE e.correspondence_id=c.id AND e.action='print') last_print_request FROM correspondence c JOIN properties p ON p.id=c.account_number JOIN users u ON u.id=c.created_by WHERE $scope".(Auth::owner()?' AND c.owner_visible=1':''),
   'documents'=>'SELECT original_filename,document_type,mime_type,file_size_bytes,version_number,owner_visible,created_at FROM documents WHERE 1=1',
   'audit'=>'SELECT l.created_at,u.full_name,l.action,l.entity_type,l.entity_id,l.ip_address FROM audit_logs l LEFT JOIN users u ON u.id=l.user_id WHERE 1=1',
  };
  if($type==='collections'){if(($filters['status']??'')==='posted')$sql.=" AND pay.status='posted'";if(!empty($filters['method'])){if(!in_array($filters['method'],['cash','bank','cheque','mobile_money'],true))throw new \DomainException('Invalid payment method.');$sql.=' AND pay.payment_method=?';$params[]=$filters['method'];}}
  if($type==='billing'&&!empty($filters['year'])){$year=filter_var($filters['year'],FILTER_VALIDATE_INT);if(!$year||$year<1900||$year>2200)throw new \DomainException('Invalid billing year.');$sql.=' AND b.billing_year=?';$params[]=$year;}
  if($type==='arrears')$params[]=today();if(!empty($filters['account_number'])&&!in_array($type,['documents','audit'],true)){$sql.=' AND p.id=?';$params[]=AccountNumber::validate($filters['account_number']);}$dateField=match($type){'billing','arrears'=>'b.issue_date','collections'=>'pay.payment_date','assessments'=>'g.effective_from','ownership'=>'o.start_date','correspondence'=>'c.created_at','documents'=>'created_at','audit'=>'l.created_at',default=>null};
  if($dateField){if(!empty($filters['from'])){$sql.=" AND $dateField>=?";$params[]=valid_date($filters['from']);}if(!empty($filters['to'])){$sql.=" AND $dateField<?";$params[]=(new \DateTimeImmutable(valid_date($filters['to'])))->modify('+1 day')->format('Y-m-d');}}
  if(!empty($filters['locality'])&&!in_array($type,['documents','audit'],true)){$sql.=' AND p.locality LIKE ?';$params[]='%'.$filters['locality'].'%';}
  return Database::all($sql.($type==='collections'?' ORDER BY pay.payment_date DESC,pay.created_at DESC,pay.id':' ORDER BY 1 DESC'),$params);
 }
 public static function export(string $type,string $format,array $filters): never {if($type==='property_contacts'&&!in_array($format,['csv','xlsx'],true))throw new \DomainException('Use CSV or Excel for the property contact export.');$rows=self::rows($type,$filters);Audit::log('report_export','reports',null,null,['type'=>$type,'format'=>$format,'rows'=>count($rows)]);if($format==='csv'){header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="srms-'.$type.'.csv"');$out=fopen('php://output','w');fwrite($out,"\xEF\xBB\xBF");$headers=$rows?array_keys($rows[0]):($type==='property_contacts'?PropertyContactReport::HEADERS:[]);if($headers)fputcsv($out,$headers,',','"','');foreach($rows as $row)fputcsv($out,array_map([PropertyContactReport::class,'csvCell'],$row),',','"','');fclose($out);exit;}if($format==='xlsx'){ $book=new \PhpOffice\PhpSpreadsheet\Spreadsheet();$sheet=$book->getActiveSheet();$sheet->setTitle('SRMS Report');if(!$rows&&$type==='property_contacts')$sheet->fromArray(PropertyContactReport::HEADERS,null,'A1');if($rows){$sheet->fromArray(array_keys($rows[0]),null,'A1');$line=2;foreach($rows as $row){$column=1;foreach($row as $v){$sheet->setCellValueExplicit([$column++,$line],(string)($v??''),\PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING);}$line++;}$sheet->getStyle('A1:'.$sheet->getHighestColumn().'1')->getFont()->setBold(true);$sheet->setAutoFilter($sheet->calculateWorksheetDimension());$sheet->freezePane('A2');}header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="srms-'.$type.'.xlsx"');(new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($book))->save('php://output');exit;}
  if($format==='pdf'){ob_start();echo '<h1>'.e(self::TYPES[$type]).'</h1><p>'.e(today()).' · GHS</p><table style="font-family:DejaVu Sans;font-size:7px;border-collapse:collapse" border="1" cellpadding="4">';if($rows){echo '<tr>';foreach(array_keys($rows[0]) as $h)echo '<th>'.e(ucwords(str_replace('_',' ',$h))).'</th>';echo '</tr>';foreach($rows as $r){echo '<tr>';foreach($r as $v)echo '<td>'.e($v).'</td>';echo '</tr>';}}echo '</table>';$pdf=Correspondence::pdf(ob_get_clean());header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="srms-'.$type.'.pdf"');echo $pdf;exit;}throw new \DomainException('Invalid export format.');
 }
}
