<?php
require dirname(__DIR__).'/app/bootstrap.php';
if(PHP_SAPI!=='cli')exit(1);
[$script,$archive,$target]=array_pad($argv,3,null);
if(!$archive||!$target||!preg_match('/^[a-zA-Z0-9_]+_restore$/',$target))throw new RuntimeException('Usage: php tools/restore.php backup.zip eddt_srms_restore. Restore requires a NEW database ending in _restore.');
$zip=new ZipArchive();if($zip->open($archive)!==true)throw new RuntimeException('Cannot read archive.');$manifest=json_decode($zip->getFromName('manifest.json'),true,512,JSON_THROW_ON_ERROR);if(($manifest['format']??'')!=='eddt-operational-backup-1')throw new RuntimeException('Use an operational backup, not a Trust export.');foreach($manifest['files'] as $path=>$hash){$bytes=$zip->getFromName($path);if($bytes===false||!hash_equals($hash,hash('sha256',$bytes)))throw new RuntimeException('Integrity check failed: '.$path);}
$pdo=new PDO('mysql:host='.config('db_host').';port='.config('db_port'),config('db_user'),config('db_password'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$s=$pdo->prepare('SELECT COUNT(*) FROM information_schema.schemata WHERE schema_name=?');$s->execute([$target]);if($s->fetchColumn())throw new RuntimeException('Target database already exists. Choose a new restore name.');$pdo->exec("CREATE DATABASE `$target` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
$mysql=getenv('SRMS_MYSQL_BIN')?:'C:/xampp/mysql/bin';$env=getenv();$env['MYSQL_PWD']=config('db_password');$dir=SRMS_ROOT.'/var/restores/'.$target;if(!mkdir($dir,0700,true))throw new RuntimeException('Cannot create restore directory.');$sql=$dir.'/database.sql';file_put_contents($sql,$zip->getFromName('database.sql'));
$proc=proc_open([$mysql.'/mysql.exe','--host='.config('db_host'),'--port='.config('db_port'),'--user='.config('db_user'),$target],[0=>['file',$sql,'r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,null,$env);$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);if(proc_close($proc)!==0)throw new RuntimeException('Restore failed; target retained for diagnosis: '.$err);unlink($sql);mkdir($dir.'/storage',0700);
foreach($manifest['files'] as $path=>$hash){if(!str_starts_with($path,'documents/'))continue;$key=substr($path,10);if(!preg_match('/^[a-f0-9-]{36}\.(pdf|jpg|png)$/',$key))throw new RuntimeException('Invalid document path.');file_put_contents($dir.'/storage/'.$key,$zip->getFromName($path));}
foreach($manifest['files'] as $path=>$hash){if(!str_starts_with($path,'application/'))continue;if(!preg_match('~^application/app/(views/letters/v[0-9]+\\.php|assets/letters/v[0-9]+/letter-(logo|watermark)\\.png)$~D',$path))throw new RuntimeException('Invalid retained template path.');$dest=$dir.'/'.$path;if(!is_dir(dirname($dest)))mkdir(dirname($dest),0700,true);file_put_contents($dest,$zip->getFromName($path));}
$pdo->exec("USE `$target`");$docs=$pdo->query('SELECT storage_key,sha256_hash FROM documents')->fetchAll(PDO::FETCH_ASSOC);foreach($docs as $doc){$p=$dir.'/storage/'.$doc['storage_key'];if(!is_file($p)||!hash_equals($doc['sha256_hash'],hash_file('sha256',$p)))throw new RuntimeException('Restored document integrity failed.');}
echo "Restore verified: $target\nStorage: $dir/storage\n".count($docs)." documents verified. Original database was not modified.\n";
