<?php
require_once __DIR__.'/ui.php';use Srms\Auth;use Srms\PropertyPayments;
$d=$dashboard;$maxMonthly=max(array_map(fn($r)=>(float)$r['amount'],$d['monthly']));$maxMethod=max(array_map(fn($r)=>(float)$r['amount'],$d['methods']));$maxYear=$d['years']?max(array_map(fn($r)=>(float)$r['billed'],$d['years'])):0;
$segments=[];$angle=0;foreach($d['statuses'] as $key=>$count){$next=$angle+($d['property_count']?($count/$d['property_count']*100):0);if($count)$segments[]=PropertyPayments::COLORS[$key].' '.$angle.'% '.$next.'%';$angle=$next;}$gradient=$segments?'conic-gradient('.implode(',',$segments).')':'#e2e8f0';
?><div class="page-heading"><div><p class="eyebrow">YOUR TRUST, AT A GLANCE</p><h1><?=e(Auth::owner()?'Your property overview':'Revenue overview')?></h1><p>Properties, payments and outstanding ground rent across your authorized records.</p></div><?php if(in_array(Auth::role(),['Administrator','Billing Officer'],true)):?><a class="button primary" href="<?=e(url('edit',['type'=>'properties']))?>">+ Register property</a><?php endif?></div>
<section class="panel form-panel"><form method="get" class="toolbar wrap"><input type="hidden" name="r" value="dashboard"><label class="field"><span>Collections year</span><input type="number" name="year" min="1900" max="2200" value="<?=e($d['selected_year']??date('Y'))?>" required></label><button class="button primary">Update charts</button><a class="button" href="<?=e(url('dashboard'))?>">Last 12 months</a><?php if(!Auth::owner()):?><a class="button" href="<?=e(url('workflows'))?>">Open workflow queues</a><?php endif?></form><p>Choose a year for collection trends. Property balances and payment status always include all outstanding bills. Select chart bars or points to inspect their records.</p></section>
<script type="application/json" id="dashboard-data"><?=json_encode($d+['base_url'=>url('reports'),'map_url'=>url('map'),'labels'=>PropertyPayments::LABELS,'colors'=>PropertyPayments::COLORS],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_THROW_ON_ERROR)?></script>
<script defer src="<?=e(config('base_url'))?>/assets/dashboard.js"></script><div class="stat-grid">
<article class="stat"><div><span>Properties</span><i aria-hidden="true">⌂</i></div><strong><?=number_format($d['property_count'])?></strong><small><?=number_format($d['account_count'])?> permanent Account numbers</small></article>
<article class="stat"><div><span>Total collected</span><i aria-hidden="true">↗</i></div><strong><em>GHS</em> <?=money($d['collected'])?></strong><small>Posted payments, all time</small></article>
<article class="stat"><div><span>Outstanding rent</span><i aria-hidden="true">◷</i></div><strong><em>GHS</em> <?=money($d['outstanding'])?></strong><small>All unpaid bills, including arrears</small></article>
<article class="stat"><div><span>Account credit</span><i aria-hidden="true">+</i></div><strong><em>GHS</em> <?=money($d['credit'])?></strong><small>Available for future bills</small></article>
</div>
<div class="charts-grid">
<section class="panel chart-panel"><div class="panel-heading"><div><h2>Monthly collections</h2><p><?=e($d['period'])?> · posted payments</p></div><span class="pill">GHS</span></div><div class="chart-body">
<?php if($maxMonthly>0):?><p class="chart-scale">Peak month: GHS <?=money((string)$maxMonthly)?></p><div class="chart-scroll" tabindex="0" aria-label="Monthly collections chart"><div class="month-bars"><?php foreach($d['monthly'] as $m):?><div class="month-column" title="<?=e($m['full_label'])?>: GHS <?=money($m['amount'])?>"><div class="month-track"><span style="height:<?=e((float)$m['amount']/$maxMonthly*100)?>%"></span></div><span><?=e($m['label'])?></span></div><?php endforeach?></div></div><?php else:?><div class="chart-empty"><strong>No collections in this period</strong><p>Posted payments will appear here by payment month.</p></div><?php endif?>
<details class="chart-data"><summary>View monthly amounts</summary><table><thead><tr><th>Month</th><th>Collected (GHS)</th></tr></thead><tbody><?php foreach($d['monthly'] as $m):?><tr><td><?=e($m['full_label'])?></td><td><?=money($m['amount'])?></td></tr><?php endforeach?></tbody></table></details></div></section>
<section class="panel chart-panel"><div class="panel-heading"><div><h2>Property payment status</h2><p>All issued bills, including arrears</p></div></div><div class="chart-body"><div class="payment-distribution"><div class="payment-donut" style="background:<?=e($gradient)?>" role="img" aria-label="Payment status distribution; counts are listed alongside"><div><strong><?=number_format($d['property_count'])?></strong><span>properties</span></div></div><ul class="payment-key"><?php foreach($d['statuses'] as $key=>$count):?><li><span><i class="map-swatch <?=e($key)?>" aria-hidden="true"></i><?=e(PropertyPayments::LABELS[$key])?></span><strong><?=number_format($count)?></strong></li><?php endforeach?></ul></div><p class="chart-note">White identifies an explicit exemption. Unbilled properties are gray; they have no issued balance yet.</p></div></section>
<section class="panel chart-panel"><div class="panel-heading"><div><h2>Billing and payments</h2><p>Most recent billed years · up to five years</p></div><span class="pill">GHS</span></div><div class="chart-body"><div class="chart-key"><span><i class="key-billed"></i>Billed, including adjustments</span><span><i class="key-paid"></i>Payments applied</span></div>
<?php if($d['years']):?><div class="year-bars"><?php foreach($d['years'] as $y):?><div class="year-row"><strong><?=e($y['billing_year'])?></strong><div><div class="amount-track" title="Billed: GHS <?=money($y['billed'])?>"><span class="key-billed" style="width:<?=e($maxYear>0?(float)$y['billed']/$maxYear*100:0)?>%"></span></div><div class="amount-track" title="Payments applied: GHS <?=money($y['paid'])?>"><span class="key-paid" style="width:<?=e($maxYear>0?(float)$y['paid']/$maxYear*100:0)?>%"></span></div></div></div><?php endforeach?></div><details class="chart-data"><summary>View annual amounts</summary><div class="table-wrap"><table><thead><tr><th>Year</th><th>Billed</th><th>Paid</th><th>Outstanding</th></tr></thead><tbody><?php foreach($d['years'] as $y):?><tr><td><?=e($y['billing_year'])?></td><td><?=money($y['billed'])?></td><td><?=money($y['paid'])?></td><td><?=money($y['outstanding'])?></td></tr><?php endforeach?></tbody></table></div></details><?php else:?><div class="chart-empty"><strong>No bills issued yet</strong><p>Annual bills and their allocated payments will appear here.</p></div><?php endif?></div></section>
<section class="panel chart-panel"><div class="panel-heading"><div><h2>Payment methods</h2><p><?=e($d['period'])?> · posted payments</p></div><span class="pill">GHS</span></div><div class="chart-body method-bars"><?php foreach($d['methods'] as $i=>$m):?><div class="method-row"><div><span><?=e($m['label'])?></span><strong><?=money($m['amount'])?></strong></div><div class="amount-track"><span class="method-<?=$i?>" style="width:<?=e($maxMethod>0?(float)$m['amount']/$maxMethod*100:0)?>%"></span></div></div><?php endforeach?><?php if(!$maxMethod):?><p class="chart-note">No posted payments in this period.</p><?php endif?></div></section>
</div>
<section class="map-callout"><div><p class="eyebrow">PROPERTY MAP</p><h2>See payment status on every parcel</h2><p>Explore boundaries, owner names and property photographs.</p></div><a class="button" href="<?=e(url('map'))?>">Open property map →</a></section>
<section class="panel"><div class="panel-heading"><div><h2>Recent payments</h2><p>Latest activity across your accounts</p></div><a class="text-link" href="<?=e(url('payments'))?>">View payments →</a></div><?php $recent=$d['recent'];foreach($recent as &$r){$r['amount']=money($r['amount']);$r['payment_method']=ucwords(str_replace('_',' ',$r['payment_method']));}unset($r);data_table($recent,['receipt_number'=>'Receipt','account_number'=>'Land account','payment_date'=>'Date','amount'=>'Amount (GHS)','payment_method'=>'Method','status'=>'Status']);?></section>