<?php
$logo='data:image/png;base64,'.base64_encode(file_get_contents(SRMS_ROOT.'/app/assets/letter-logo.png'));
$watermark='data:image/png;base64,'.base64_encode(file_get_contents(SRMS_ROOT.'/app/assets/letter-watermark.png'));
$printedLabel=date('jS F, Y',strtotime($vars['printed']));
?><!doctype html><html><head><meta charset="utf-8"><style>@page{margin:22px 30px 35px}body{font-family:"Times-Roman",serif;font-size:12px;color:#000;line-height:1.28}p{margin:0 0 13px}header{height:103px;border-bottom:5px solid #000;text-align:center;color:#d50000;position:relative}header h1{font-size:22px;font-weight:normal;margin:0 0 2px}header .address{font-size:17px;margin:0}header .act{font-size:11px;margin:5px 0}header .contact{font-size:11px}header .logo{position:absolute;left:16px;top:31px;width:90px;height:63px}.watermark{position:fixed;left:0;top:185px;width:530px;z-index:-1}main{padding:13px 20px}h2{font-size:13px;text-decoration:underline;text-align:center;margin:10px 0 15px}table{border-collapse:collapse;width:100%;margin:9px 0}th,td{border:1px solid #333;padding:4px;text-align:center;font-size:10px}th{font-weight:normal}.meta{font-size:10px;margin:0 0 12px}.meta span{float:right}.warning{font-weight:bold;font-style:italic;text-decoration:underline;font-size:11px}.photo{display:block;max-width:335px;max-height:190px;margin:12px auto}.photo-placeholder{height:100px;text-align:center;color:#666;font-style:italic;padding-top:40px}.qr{width:88px;height:88px;margin-top:8px}.sign{font-size:10px;text-align:right;margin-top:16px}.foot{position:fixed;bottom:-16px;left:0;right:0;border-bottom:5px solid #000;padding-bottom:7px;font-size:8px;color:#555}.body-text{font-size:12px;line-height:1.45}.contact-line{font-size:11px;margin-top:12px}.receipt td,.receipt th{text-align:left;font-size:12px;padding:9px}.small{font-size:9px}.notice-heading{font-variant:small-caps;text-align:center;margin-bottom:0}</style></head><body>
<img class="watermark" src="<?=e($watermark)?>" alt=""><header><h1><?=e($settings['organization_name'])?></h1><img class="logo" src="<?=e($logo)?>" alt="EDDT"><p class="address"><?=e($settings['address'])?></p><p class="act">ESTABLISHED UNDER THE LAND ACT 2020</p><p class="contact"><?=e($settings['digital_address'])?> / Email: <?=e($settings['email'])?></p></header><main>
<p class="meta">DATE PRINTED: <?=e(strtoupper($printedLabel))?><span>LAND ACCOUNT NUMBER: <b><?=e($account['land_account_number']?:$account['account_number'])?></b></span></p>
<?php if($type==='demand_notice'):?><h2>GROUND RENT DEMAND NOTICE</h2><p><b>Lessee name: <u><?=e(($owner['organization_name']??'')?:($owner['full_name']??'PROPERTY OWNER'))?></u><br>The East Dadekotopon Development Trust (EDDT) is by this notice serving you your Ground Rent Demand Notice for <?=e($year)?> since the bill has not been settled.</b></p><p class="warning"><?=e($settings['demand_warning']??'')?></p><p class="notice-heading">East Dadekotopon Development Trust</p><table><tr><th>Account Number</th><th>Plot size / <?=e($property['plot_size_unit']?:'Acreage')?></th><th>Description</th><th>Current</th><th>Arrears</th><th>Total Rent Due</th></tr><tr><td><?=e($account['land_account_number']?:$account['account_number'])?></td><td><?=e($property['plot_size'])?></td><td><?=e($property['land_description'])?></td><td><?=money($current)?></td><td><?=money($arrears)?></td><td><b><?=money($vars['total'])?></b></td></tr></table><p class="small">All amounts in GHS · Service period: <?=e($year)?> annual ground rent · Land ID: <?=e($property['land_id'])?> · Available credit: GHS <?=money($account['credit_amount'])?></p>
<?php if($photoData):?><img class="photo" src="<?=e($photoData)?>" alt="Property photograph"><?php else:?><div class="photo-placeholder">Property photograph not yet recorded</div><?php endif?><p>• Payment must be made before <b><?=e(date('jS F, Y',strtotime($bill['payment_deadline']?:$bill['due_date'])))?></b>. Please insist on an official receipt.<br>• Please come to the office at <?=e($settings['address'])?> with a copy of your indenture.</p>
<?php elseif($type==='invitation'):?><p><b>Dear Sir/Madam,</b></p><h2>INVITATION TO UPDATE / PRODUCE AND CORRECT LAND DOCUMENTS</h2><div class="body-text"><?php $body=\Srms\LetterTemplates::render($settings['invitation_body'],['period_from'=>date('jS F, Y',strtotime($from)),'period_to'=>date('jS F, Y',strtotime($to)),'address'=>$settings['address'],'phone'=>$settings['phone'],'email'=>$settings['email'],'owner'=>($owner['organization_name']??'')?:($owner['full_name']??'Property Owner'),'land_account_number'=>$account['land_account_number']?:$account['account_number']]);foreach(explode("\n\n",$body) as $paragraph):?><p><?=nl2br(e($paragraph))?></p><?php endforeach?></div>
<?php else:?><h2>GROUND RENT PAYMENT RECEIPT</h2><p>Property: <?=e($property['property_number'])?> · Land ID: <?=e($property['land_id'])?></p><table class="receipt"><tr><th>Receipt number</th><td><?=e($payment['receipt_number'])?></td></tr><tr><th>Date paid</th><td><?=e($payment['payment_date'])?></td></tr><tr><th>Payer</th><td><?=e($payment['payer_name'])?></td></tr><tr><th>Method / reference</th><td><?=e($payment['payment_method'])?> / <?=e($payment['external_reference'])?></td></tr><tr><th>Amount received</th><td><b>GHS <?=money($payment['amount'])?></b></td></tr><tr><th>Status at issue</th><td><?=e(strtoupper($payment['status']))?></td></tr></table><p>This receipt records a payment. Sign in to confirm its current status and allocation.</p><?php endif?>
<p class="contact-line">CONTACT NUMBER <b><?=e($settings['phone']?:'See Trust office')?></b> &nbsp;&nbsp;&nbsp; DIGITAL ADDRESS <b><?=e($settings['digital_address'])?></b></p><img class="qr" src="<?=e($qr)?>" alt="Secure account QR code"><p class="small">Scan to view your account. Secure sign-in is required.</p><p class="sign"><?=e($settings['signatory']??'ADMINISTRATOR EDDT')?></p></main><div class="foot"><?=e($ref)?> · Archived correspondence · Template 2</div></body></html>
