<?php require_once __DIR__.'/ui.php';use Srms\Database as DB;page_heading('Batch letters','Preview recipients, save correspondence records, and download one combined PDF for printing.');?>
<?php if($batch):$params=json_decode($batch['parameters_json'],true);$counts=array_count_values(array_column($items,'status'));?>
<section class="panel form-panel"><h2><?=e(ucwords(str_replace('_',' ',$batch['correspondence_type'])))?> batch</h2><p><?=count($items)?> properties · Created <?=e($batch['created_at'])?></p><p id="letter-progress" role="status"><?=e($batch['status'])?>: <?=e($counts['completed']??0)?> completed, <?=e($counts['skipped']??0)?> skipped, <?=e($counts['failed']??0)?> failed.</p>
<?php if($batch['status']!=='completed'&&in_array(\Srms\Auth::role(),['Administrator','Billing Officer'],true)):?><form method="post" action="<?=e(url('letter-batch-run'))?>" id="letter-run-form"><?=csrf_field()?><?php hidden('id',$batch['id']);?><button class="button primary" type="submit">Generate / resume letters</button></form><p>Keep this page open while generating. You may stop and resume later; completed letters are preserved.</p><?php endif?>
<form class="correspondence-actions" method="post" target="_blank" id="letter-download" <?=($batch['status']==='completed'?'':'hidden')?> action="<?=e(url('letter-batch-download'))?>"><?=csrf_field()?><?php hidden('id',$batch['id']);hidden('request_key',uuid());?><button class="button" name="action" value="preview">Preview</button><button class="button" name="action" value="print">Print combined PDF</button><button class="button" name="action" value="download">Download combined PDF</button></form> <a href="<?=e(url('letter-batches'))?>">New batch</a></section>
<section class="panel"><h2>Batch records</h2><div class="table-wrap"><table><thead><tr><th>Account number</th><th>Status</th><th>Result</th></tr></thead><tbody><?php foreach($items as $item):?><tr><td><?=e($item['account_number'])?></td><td><?=e($item['status'])?></td><td><?php if($item['correspondence_id']):?><a href="<?=e(url('detail',['type'=>'parcels','id'=>$item['account_number']]))?>">Correspondence on property</a><?php elseif($item['document_id']):?><a href="<?=e(url('download',['id'=>$item['document_id']]))?>">Archived letter</a><?php else:?><?=e($item['error_message'])?><?php endif?></td></tr><?php endforeach?></tbody></table></div></section>
<script defer src="<?=e(config('base_url'))?>/assets/letter-batches.js"></script>
<?php else:?>
<?php if(in_array(\Srms\Auth::role(),['Administrator','Billing Officer'],true)):?><section class="panel form-panel"><h2>Choose recipients</h2><p>Up to 500 properties per batch. Demand notices require a bill for the chosen year and an outstanding balance through that year; exempt properties are excluded. Invitations can include properties that have not been billed. Only active properties are included.</p><form method="get" action="<?=e(config('base_url'))?>/index.php" class="form-grid"><?php hidden('r','letter-batches');hidden('preview','1');field('type','Letter type',$_GET['type']??'demand_notice','select',true,['demand_notice'=>'Demand notices','invitation'=>'Invitation letters']);field('year','Demand notice billing year',$_GET['year']??date('Y'),'number',true);field('printed_date','Issue date',$_GET['printed_date']??today(),'date',true);field('locality','Locality contains',$_GET['locality']??'');field('accounts','Account numbers (optional; separate with commas or new lines)',$_GET['accounts']??'','textarea');field('include_unassigned','Include properties without a recorded owner',!empty($_GET['include_unassigned']),'checkbox');field('period_from','Invitation period starts',$_GET['period_from']??'','date');field('period_to','Invitation period ends',$_GET['period_to']??'','date');submit('Preview recipients');?></section>
<?php if($preview!==null):?><section class="panel form-panel"><h2><?=count($preview)>500?'More than 500':count($preview)?> eligible properties</h2><p>Properties outside these filters, without the required bill, or without owners (unless included above) are not selected.</p><?php if($preview&&count($preview)<=500):form_start('letter-batch-create');echo token_field();foreach(['type','year','printed_date','locality','accounts','include_unassigned','period_from','period_to'] as $key)hidden($key,$_GET[$key]??'');submit('Create this batch');?><?php else:?><p>Adjust the filters to select between 1 and 500 properties.</p><?php endif?><?php data_table(array_slice($preview,0,500),['account_number'=>'Account number','locality'=>'Locality']);?></section><?php endif?>
<?php endif?><section class="panel"><h2>Previous batches</h2><?php foreach($batches as $b):?><a class="record-link" href="<?=e(url('letter-batches',['id'=>$b['id']]))?>"><?=e($b['created_at'].' · '.ucwords(str_replace('_',' ',$b['correspondence_type'])))?><span><?=e($b['status'])?></span></a><?php endforeach?><?php if(!$batches):?><p>No letter batches yet.</p><?php endif?></section>
<?php endif?>
