<?php
require_once __DIR__.'/ui.php';
use Srms\Auth;
page_heading($title,'Search receipts, review collection totals, generate receipt PDFs and correct transactions through audited reversals.');
?>
<?php if(in_array(Auth::role(),['Administrator','Billing Officer'],true)):?><div class="actions"><a class="button primary" href="<?=e(url('payment-new'))?>">Record payment</a></div><?php endif?>
<div class="summary-strip">
    <article class="summary-card"><span class="summary-label">Posted total</span><strong class="summary-value">GHS <?=money($summary['posted_total'])?></strong><span class="summary-meta">Matching filters</span></article>
    <article class="summary-card"><span class="summary-label">Posted receipts</span><strong class="summary-value"><?=number_format((int)$summary['posted_count'])?></strong><span class="summary-meta">Active transactions</span></article>
    <article class="summary-card"><span class="summary-label">Reversed</span><strong class="summary-value"><?=number_format((int)$summary['reversed_count'])?></strong><span class="summary-meta">Preserved audit history</span></article>
    <article class="summary-card"><span class="summary-label">Results</span><strong class="summary-value"><?=number_format($total)?></strong><span class="summary-meta">Payments found</span></article>
</div>
<section class="panel">
    <form class="toolbar" method="get"><input type="hidden" name="r" value="payments">
        <?php field('q','Receipt, Account or payer',$q,'search');field('method','Method',$method,'select',false,['cash'=>'Cash','bank'=>'Bank transfer','cheque'=>'Cheque','mobile_money'=>'Mobile money']);field('status','Status',$status,'select',false,['posted'=>'Posted','reversed'=>'Reversed']);field('from','From',$_GET['from']??'','date');field('to','To',$_GET['to']??'','date');?>
        <button class="button primary">Apply filters</button><a class="button" href="<?=e(url('payments'))?>">Clear</a>
    </form>
    <?php if(!$rows):data_table([]);else:?><div class="table-wrap"><table><thead><tr><th>Receipt</th><th>Account</th><th>Date</th><th>Payer / reference</th><th>Method</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody>
    <?php foreach($rows as $row):?><tr><td><strong><?=e($row['receipt_number'])?></strong></td><td><a href="<?=e(url('detail',['type'=>'parcels','id'=>$row['account_number']]))?>"><?=e($row['account_number'])?></a><small class="cell-sub"><?=e($row['locality']?:'')?></small></td><td><?=e($row['payment_date'])?></td><td><?=e($row['payer_name']?:'—')?><small class="cell-sub"><?=e($row['external_reference']?:'')?></small></td><td><?=e(ucwords(str_replace('_',' ',$row['payment_method'])))?></td><td>GHS <?=money($row['amount'])?></td><td><?=badge($row['status'])?><?php if($row['reversal_reason']):?><small class="cell-sub"><?=e($row['reversal_reason'])?></small><?php endif?></td><td><?php if($row['correspondence_id']):?><form class="correspondence-actions" method="post" target="_blank" action="<?=e(url('correspondence-output'))?>"><?=csrf_field()?><?php hidden('id',$row['correspondence_id']);hidden('request_key',uuid());?><button class="button small" name="action" value="preview">Receipt</button><button class="button small" name="action" value="print">Print</button><button class="button small" name="action" value="download">Download</button></form><?php endif?><?php if(in_array(Auth::role(),['Administrator','Billing Officer'],true)):?><form method="post" action="<?=e(url('correspondence'))?>"><?=csrf_field()?><?php hidden('type','receipt');hidden('account_number',$row['account_number']);hidden('payment_id',$row['id']);?><button class="button small">Save receipt</button></form><?php if(Auth::role()==='Administrator'&&$row['status']==='posted'):?><details class="row-action"><summary>Reverse</summary><form method="post" action="<?=e(url('reverse'))?>"><?=csrf_field()?><?php hidden('id',$row['id']);?><label class="field"><span>Reason</span><textarea name="reason" required></textarea></label><button class="button small" type="submit">Confirm reversal</button></form></details><?php endif?><?php endif?></td></tr><?php endforeach?></tbody></table></div><?php endif?>
    <div class="pagination"><span>Page <?=$page?> of <?=max(1,ceil($total/$size))?></span><div class="actions"><?php $filters=['q'=>$q,'method'=>$method,'status'=>$status,'from'=>$_GET['from']??'','to'=>$_GET['to']??''];if($page>1):?><a class="button small" href="<?=e(url('payments',$filters+['page'=>$page-1]))?>">Previous</a><?php endif?><?php if($page*$size<$total):?><a class="button small" href="<?=e(url('payments',$filters+['page'=>$page+1]))?>">Next</a><?php endif?></div></div>
</section>
